### ISSUE TITLE
[Bug]: After the upgrade to 2026.4.21, the program could not be launched.

### ISSUE THREAD

**Issue by kinlioncd** [clawdbot/clawdbot#70613]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

The 2026.4.21 version upgrade failed again. After the upgrade, Openclaw couldn't run.
After installing npm install -g @larksuiteoapi/node-sdk, Openclaw could run, but WeChat could not be used. What a garbage software! It crashes every time I upgrade it.

### Steps to reproduce

yuhuang@yuhuang-PC:~$ openclaw gateway restart
Failed to read config at /home/yuhuang/.openclaw/openclaw.json Error: Cannot find module '@larksuiteoapi/node-sdk'
Require stack:
- /home/yuhuang/.npm-global/lib/node_modules/openclaw/dist/extensions/feishu/client-yWGpoGkZ.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at Function.resolve (node:internal/modules/helpers:157:19)
    at jitiResolve (/home/yuhuang/.npm-global/lib/node_modules/openclaw/node_modules/jiti/dist/jiti.cjs:1:148703)
    at jitiRequire (/home/yuhuang/.npm-global/lib/node_modules/openclaw/node_modules/jiti/dist/jiti.cjs:1:150290)
    at /home/yuhuang/.npm-global/lib/node_modules/openclaw/node_modules/jiti/dist/jiti.cjs:1:157987
    at /home/yuhuang/.npm-global/lib/node_modules/openclaw/dist/extensions/feishu/client-yWGpoGkZ.js:3:36
    at eval_evalModule (/home/yuhuang/.npm-global/lib/node_modules/openclaw/node_modules/jiti/dist/jiti.cjs:1:155533)
    at jitiRequire (/home/yuhuang/.npm-global/lib/node_modules/openclaw/node_modules/jiti/dist/jiti.cjs:1:150967)
    at /home/yuhuang/.npm-global/lib/node_modules/openclaw/node_modules/jiti/dist/jiti.cjs:1:157987
    at /home/yuhuang/.npm-global/lib/node_modules/openclaw/dist/extensions/feishu/drive-CqL2E2AR.js:2:23 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/yuhuang/.npm-global/lib/node_modules/openclaw/dist/extensions/feishu/client-yWGpoGkZ.js'
  ]
}

🦞 OpenClaw 2026.4.21 (f788c88)
   I'm the assistant your terminal demanded, not the one your sleep schedule requested.

Config invalid
File: ~/.openclaw/openclaw.json
Problem:
  - <root>: read failed: Error: Cannot find module '@larksuiteoapi/node-sdk'\nRequire stack:\n- /home/yuhuang/.npm-global/lib/node_modules/openclaw/dist/extensions/feishu/client-yWGpoGkZ.js                               

Run: openclaw doctor --fix
Gateway aborted: config is invalid.
<root>: read failed: Error: Cannot find module '@larksuiteoapi/node-sdk'\nRequire stack:\n- /home/yuhuang/.npm-global/lib/node_modules/openclaw/dist/extensions/feishu/client-yWGpoGkZ.js
Fix the config and retry, or run "openclaw doctor" to repair.

### Expected behavior

After the upgrade on April 21, 2026, the program could not be launched.

### Actual behavior

After the upgrade on April 21, 2026, the program could not be launched.

### OpenClaw version

2026.4.21

### Operating system

ubuntu22.04

### Model

openrouter

### Provider / routing chain

openclaw

### Logs, screenshots, and evidence

```shell

```

**Comment by steipete** [comment]
Closing as fixed in `2026.4.22`.

This report is the same `2026.4.21` bundled plugin runtime-dependency regression as the main cluster: `@larksuiteoapi/node-sdk` was missing when the Feishu bundled plugin was loaded during config/gateway startup.

Verified against the published `openclaw@2026.4.22` package:

- Fresh temp install with Feishu + Telegram configured and staged deps initially missing.
- `openclaw doctor --fix --non-interactive` installed `@larksuiteoapi/node-sdk`, `grammy`, and Telegram runtime deps successfully.
- Separate `gateway run` smoke reached `ready`; no `MODULE_NOT_FOUND` crash.

Upgrade/recovery:

```bash
npm install -g openclaw@latest
openclaw doctor --fix
openclaw gateway restart
```

If this exact `Cannot find module ...` failure reproduces on `2026.4.22` or newer, please open a fresh issue with the version, install method, command, and full require stack.
