### ISSUE TITLE
[Bug]: OpenClaw 2026.4.21 update leaves broken install: missing @larksuiteoapi/node-sdk, then postinstall fails on unsafe dist entry ... fxparser

### ISSUE THREAD

**Issue by Chunlyn00** [clawdbot/clawdbot#70343]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After updating OpenClaw from 2026.4.15 to 2026.4.21, openclaw status --deep fails with missing module @larksuiteoapi/node-sdk, and npm install --legacy-peer-deps then fails in postinstall on an unsafe dist entry under dist/extensions/amazon-bedrock-mantle/node_modules/.bin/fxparser.

## Summary

Updating OpenClaw from `2026.4.15` to `2026.4.21` succeeded at the package-version level, but the installation was left broken.

After restart, `openclaw status --deep` failed with a missing module error:

```text
Error: Cannot find module '@larksuiteoapi/node-sdk'
Require stack:
- /home/claw/.npm-global/lib/node_modules/openclaw/dist/extensions/feishu/client-yWGpoGkZ.js

Attempting to repair the install with npm install hit a peer dependency conflict, and npm install --legacy-peer-deps then failed in OpenClaw’s postinstall script with:

Error: unsafe dist entry: dist/extensions/amazon-bedrock-mantle/node_modules/.bin/fxparser

So the update path appears to leave the install in a broken state, and the obvious repair path also fails.

Environment

• OpenClaw before update: 2026.4.15
• OpenClaw target version: 2026.4.21
• OS: Linux
• Node: v22.22.2
• Install path: /home/claw/.npm-global/lib/node_modules/openclaw

What I ran

Update

openclaw update --yes

This reported:

• Before: 2026.4.15
• After: 2026.4.21

Restart / verify

openclaw gateway restart
openclaw status --deep

First failure

openclaw status --deep failed with:

[openclaw] Failed to start CLI: Error: Cannot find module '@larksuiteoapi/node-sdk'
Require stack:
- /home/claw/.npm-global/lib/node_modules/openclaw/dist/extensions/feishu/client-yWGpoGkZ.js

Attempted repair

Plain npm install

cd /home/claw/.npm-global/lib/node_modules/openclaw
npm install

This failed with ERESOLVE around:

• madge@8.0.0
• typescript@6.0.3
• peerOptional typescript@"^5.4.4"

Legacy peer deps fallback

cd /home/claw/.npm-global/lib/node_modules/openclaw
npm install --legacy-peer-deps

This got past the peer conflict, but failed in postinstall:

Error: unsafe dist entry: dist/extensions/amazon-bedrock-mantle/node_modules/.bin/fxparser
    at listInstalledDistFiles (file:///home/claw/.npm-global/lib/node_modules/openclaw/scripts/postinstall-bundled-plugins.mjs:203:15)
    at pruneInstalledPackageDist (file:///home/claw/.npm-global/lib/node_modules/openclaw/scripts/postinstall-bundled-plugins.mjs:289:26)
    at runBundledPluginPostinstall (file:///home/claw/.npm-global/lib/node_modules/openclaw/scripts/postinstall-bundled-plugins.mjs:709:27)

### Expected behavior

• openclaw update --yes should leave the install in a working state
• openclaw status --deep should run successfully after restart
• repair steps should not fail on missing packaged dependencies or postinstall dist-pruning checks


### Actual behavior

• update claims success
• restart happens
• CLI is broken by missing packaged dependency
• repair path fails on postinstall script safety check

### OpenClaw version

2026.4.21 (f788c88)

### Operating system

Linux 6.8.0-110-generic (x64)

### Install method

npm global

### Model

N/A — failure occurs in CLI/update/install path before model execution

### Provider / routing chain

N/A — CLI/update/install failure before provider selection or model routing  Configured routing at time of failure: primary anthropic/claude-sonnet-4-6, with fallbacks including openai-codex/gpt-5.4, groq/llama-3.3-70b-versatile, and ollama/qwen2.5-coder:7b.

### Additional provider/model setup details

_No response_

### Logs, screenshots, and evidence

```shell

```

### Additional information

Updated from 2026.4.15 to 2026.4.21 via openclaw update --yes.
1. missing bundled dependency for Feishu extension (@larksuiteoapi/node-sdk)
2. postinstall script rejecting a .bin entry under dist/extensions/amazon-bedrock-mantle/node_modules/.bin/fxparser

[2026-04-22T20_42_16_849Z-debug-0.log](https://github.com/user-attachments/files/26986666/2026-04-22T20_42_16_849Z-debug-0.log)

[2026-04-22T20_46_07_089Z-debug-0.log](https://github.com/user-attachments/files/26986670/2026-04-22T20_46_07_089Z-debug-0.log)

**Comment by steipete** [comment]
Fixed on `main`.

This had two bundled-install pieces, both now covered:

- postinstall pruning no longer treats staged packaged `dist/extensions/*/node_modules` entries such as `.bin/fxparser` as unsafe install targets.
- packaged bundled plugin runtime deps are repaired when the bundled plugin activates, and read-only discovery now skips/caches load failures instead of crashing on missing Feishu/Lark deps.

Newest hardening commit: openclaw/openclaw@9b1f1036acb286b4d0400da62f09bcb7d0437e4f. I also added Docker E2E coverage for packaged install + synthetic bundled channel loader failures so this path is reproducible outside a maintainer machine.

This will be in the next npm release after 2026.4.21. Closing as fixed on main.
