### ISSUE TITLE
memory-lancedb-pro v1.0.32: plugin tool fails with TypeError: stringEnum is not a function (OpenClaw 2026.4.12)

### ISSUE THREAD

**Issue by GeoffKellyNC** [clawdbot/clawdbot#66195]
## Bug Report

**Plugin:** memory-lancedb-pro v1.0.32
**OpenClaw version:** 2026.4.12 (1c0672b)
**Platform:** Linux (Node v22.22.2)

### Summary

After upgrading OpenClaw to 2026.4.12, the memory-lancedb-pro plugin initializes successfully but all plugin **tool calls fail** immediately with:

```
TypeError: (0 , _pluginSdk.stringEnum) is not a function
```

The plugin loads, connects to LanceDB, and injects memories into context. But auto-capture (writing new memories during conversation) does not work because every tool registration call fails.

### Root Cause

In `src/tools.ts`, the plugin imports `stringEnum` from `openclaw/plugin-sdk`:

```ts
import { stringEnum } from "openclaw/plugin-sdk";
```

This function appears to have been **removed or renamed** in the `openclaw/plugin-sdk` exported by OpenClaw 2026.4.12. The import resolves but calling it throws at runtime.

The error is accompanied by this deprecation warning:
```
[OPENCLAW_PLUGIN_SDK_COMPAT_DEPRECATED] Warning: openclaw/plugin-sdk/compat is deprecated for new plugins. Migrate to focused openclaw/plugin-sdk/<subpath> imports.
```

### Observed Behavior

- Plugin initialization: ✅ `initialized successfully (embedding: OK, retrieval: OK, mode: hybrid, FTS: enabled)`
- Memory recall/inject on session start: ✅ Working
- Auto-capture (write new memories): ❌ Fails silently — `plugin tool failed (memory-lancedb-pro): TypeError: (0 , _pluginSdk.stringEnum) is not a function`
- Backup: ✅ Working

### Impact

Real-time memory capture is completely non-functional. Users lose all conversation context unless they manually update MEMORY.md.

### Expected Fix

Either:
1. Restore `stringEnum` export to `openclaw/plugin-sdk` (or compat layer) in OpenClaw 2026.4.12+
2. Update memory-lancedb-pro to replace `stringEnum` with a local implementation (e.g. `Type.Union(values.map(v => Type.Literal(v)))` from `@sinclair/typebox`)

### Workaround

None available to end users. The plugin source can be patched manually but requires rebuilding.

**Comment by Artyomkun** [comment]
@steipete 
Fixed, closed.

**Comment by steipete** [comment]
Codex maintainer triage: closing this into #68279 as the current canonical tracker for the bare `openclaw/plugin-sdk` missing `stringEnum` / `optionalStringEnum` compatibility break. Current `main` still returns `undefined` for both helpers from `src/plugin-sdk/index.ts`, while `src/plugin-sdk/core.ts` exports them; PR #66214 is the active fix attempt and needs baseline/test/docs follow-through before merge.
