### ISSUE TITLE
v2026.4.21: WhatsApp plugin fails to load — @whiskeysockets/baileys missing from distribution; watchdog reinstalls broken version without health-gate

### ISSUE THREAD

**Issue by azeemazhar2** [clawdbot/clawdbot#70545]
## Summary

Two related bugs that caused a complete WhatsApp outage on upgrade to v2026.4.21.

## Bug 1 — Baileys missing from distribution

**Version:** 2026.4.21  
**Node:** v24.13.1 (plist) / v25.6.1 (running)  
**Platform:** macOS (Apple Silicon)

After upgrading to v2026.4.21, the WhatsApp plugin fails to load on every gateway start:

```
[plugins] whatsapp failed during register from .../openclaw/dist/extensions/whatsapp/index.js:
Error: Cannot find module '@whiskeysockets/baileys'
Require stack:
- .../openclaw/dist/extensions/whatsapp/auth-store-DY1p5mrF.js
```

Also accompanied by:

```
refresh failed: Cannot find module './channel.runtime-CDQh58UM.js'
Require stack:
- .../openclaw/dist/extensions/whatsapp/state-migrations-4tjOx7wh.js
```

The prior version (2026.4.15) worked correctly. The `@whiskeysockets/baileys` dependency appears to be missing from the npm distribution bundle for this release. Rolling back to 2026.4.15 restored normal operation.

## Bug 2 — Watchdog reinstalls broken version without health-gate

The LaunchDaemon watchdog (`ai.openclaw.gateway.watchdog`) runs `openclaw gateway install --force` when it detects the gateway is down. When it ran after the broken upgrade, it:

1. Reinstalled the same broken v2026.4.21 (latest on npm = still broken)
2. Declared "reinstall succeeded" based on `launchctl load` success alone
3. Never verified that WhatsApp (or any plugin) actually loaded correctly

**Expected behaviour:** After `install --force`, the watchdog should run a plugin health check (e.g. verify WhatsApp channel is registered) and roll back to a known-good backup if the check fails.

**Actual behaviour:** Watchdog reinstalls → declares success → gateway restarts into broken state on loop.

## Impact

- WhatsApp was completely dark from 03:17–08:00 BST
- No automated alert fired (primary alert channel was the broken channel)
- Required manual user intervention to fix

## Suggested Fixes

1. Ensure `@whiskeysockets/baileys` is bundled correctly in the v2026.4.21 npm distribution
2. Add a post-install health check to the watchdog before declaring success — at minimum, verify that whatsapp plugin registers without error
3. If health check fails, roll back to the `.bak` plist backup and alert via a secondary channel (Telegram, Discord, etc.)

## Repro

```
npm install -g openclaw@2026.4.21
openclaw gateway restart
# WhatsApp plugin fails immediately
```

**Comment by steipete** [comment]
Closing the `2026.4.21` missing bundled dependency part as fixed in `2026.4.22`.

The WhatsApp `@whiskeysockets/baileys` failure is part of the same bundled-runtime-deps packaging/runtime repair cluster as the Feishu/Telegram/Slack/Nostr reports from `2026.4.20` / `2026.4.21`. The released `.22` path now repairs/stages bundled runtime deps instead of failing with `MODULE_NOT_FOUND`; the related cluster has been verified and closed.

Recovery:

```bash
npm install -g openclaw@latest
openclaw doctor --fix
openclaw gateway restart
```

Note: this issue also mentions a separate watchdog/rollback health-gate improvement. That is a different hardening request from the missing-dependency regression. If it is still wanted, please open a focused issue for watchdog post-install health checks / rollback behavior with the expected policy. Keeping this mixed issue open would make the already-fixed `.21` packaging regression look unresolved.
