### ISSUE TITLE
**[Bug]: 2026.4.25 — `chokidar` missing from plugin-runtime-deps bundle; `openclaw memory status` fails with ERR_MODULE_NOT_FOUND after upgrade**

### ISSUE THREAD

**Issue by shrimpy8** [clawdbot/clawdbot#72882]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After upgrading from 2026.4.24 to 2026.4.25 via `openclaw update`, the `openclaw memory status` CLI command fails immediately with:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'chokidar' imported from
~/.openclaw/plugin-runtime-deps/openclaw-2026.4.25-7a0a182eed63/dist/manager-C6O7HXGc.js
Did you mean to import "chokidar/index.js"?
```

Running `openclaw doctor --fix` reports all bundled plugin runtime deps as installed and completes without error, but `chokidar` is still absent from the plugin-runtime-deps directory after `--fix` completes:

```
ls ~/.openclaw/plugin-runtime-deps/openclaw-2026.4.25-7a0a182eed63/node_modules/ | grep chokidar
# (no output — chokidar not present)
```

### Steps to reproduce

1. Run the upgrade script or `openclaw update` from 2026.4.24 → 2026.4.25
   (npm global install, Linux, node 24.14.1)

2. After upgrade completes and gateway is running, run:
   openclaw memory status

3. Observe ERR_MODULE_NOT_FOUND for `chokidar` from:
   ~/.openclaw/plugin-runtime-deps/openclaw-2026.4.25-7a0a182eed63/dist/manager-C6O7HXGc.js

4. Run openclaw doctor --fix
   Observe: doctor reports all bundled plugin deps installed, completes without error.

5. Run openclaw memory status again.
   Observe: same ERR_MODULE_NOT_FOUND — chokidar still missing.

6. Verify chokidar is absent from the bundle:
   ls ~/.openclaw/plugin-runtime-deps/openclaw-2026.4.25-7a0a182eed63/node_modules/ | grep chokidar
   (no output)

7. Workaround:
   cd ~/.openclaw/plugin-runtime-deps/openclaw-2026.4.25-7a0a182eed63
   npm install chokidar
   openclaw memory status
   (now succeeds)

### Expected behavior

openclaw doctor --fix installs chokidar into the plugin-runtime-deps bundle, or the 2026.4.25 package includes it.

### Actual behavior

chokidar is absent after both the upgrade and doctor --fix. Manual install inside the bundle directory is the only fix.

### OpenClaw version

2026.4.25 (aa36ee6)

### Operating system

Linux Mint, linux 6.8.0-110-generic x64, node 24.14.1

### Install method

npm global (`npm install -g openclaw` via `openclaw update`)

### Model

Claude-sonnet-4.5

### Provider / routing chain

openrouter

### Logs, screenshots, and evidence

```shell

```

### Impact and severity

- `openclaw memory status` is broken out of the box after upgrade until the manual workaround is applied
- Gateway and memory plugin function correctly (Telegram responds, memory recall works from agent turns) — this is a CLI-only breakage
- `openclaw doctor --fix` does not detect or repair the missing `chokidar` dep

### Additional information

**Workaround**

Manually installing `chokidar` inside the plugin-runtime-deps bundle resolves the CLI error:

```bash
cd ~/.openclaw/plugin-runtime-deps/openclaw-2026.4.25-7a0a182eed63
npm install chokidar
```

After this, `openclaw memory status` returns correct output and memory is fully operational.

**Note:** `npm install chokidar` also removed 425 existing packages from that directory (the bundle had no package.json locking them), so `openclaw doctor --fix` was run again afterwards to restore the other bundled deps.

**Related issues**

This appears to be another surface of the bundled plugin runtime dep staging regression tracked in #69842, #67038, #61686. The specific detail here is that `chokidar` is not included in the deps list that `openclaw doctor --fix` installs into `plugin-runtime-deps`, despite being required by `dist/manager-C6O7HXGc.js`.

**Comment by kasnol** [comment]
For those who are stuck on this issue:
What was wrong:

memory-core was failing because the plugin runtime sandbox was missing chokidar.
Error was: Cannot find module 'chokidar'

What I did, I asked gpt-5.5 in terminal ui to :

Reinstalled the plugin runtime dependency set.
Added chokidar@5.0.0 into the runtime deps sandbox.
Gateway is running and RPC is OK.
Evidence:

chokidar now resolves from:
~/.openclaw/plugin-runtime-deps/openclaw-2026.4.25-fa742a1beb9f/node_modules/chokidar/index.js
Gateway now reports:
ready (7 plugins: acpx, active-memory, anthropic, discord, memory-core, memory-wiki, telegram)

**Comment by steipete** [comment]
Confirmed against the shipped 2026.4.25 package: `memory-core` declares `chokidar`, but the 2026.4.25 doctor/runtime-deps repair path can miss it, so `openclaw memory status` can fail with `ERR_MODULE_NOT_FOUND` after update.

This is fixed on `main` by the post-2026.4.25 doctor/runtime-deps changes. The important behavior change is that doctor now scopes bundled runtime-deps repair through the effective startup plugin set, so the default memory slot includes `memory-core` and stages `chokidar` before memory CLI/runtime loads.

Verification I ran on Blacksmith Testbox with a packed current `openclaw@2026.4.26` tarball installed into a clean temp prefix/HOME:

- `openclaw doctor --fix` reported `chokidar@^5.0.0 (used by memory-core)` as missing
- the repair installed `chokidar@^5.0.0` into the managed plugin-runtime-deps root
- no `openclaw-unknown-*` root was created
- `openclaw memory status --json` completed from the installed package

Closing as fixed on `main`/next package. Please reopen or file a fresh issue if this still reproduces after updating past 2026.4.25.
