### PR TITLE
fix(telegram): align grammy version spec to installed 1.41.x

### LINKED ISSUE #70137: [Bug]: Post 4.21 update; "Cannot find module `grammy`", maybe telegram related.
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After installing the 2026.4.21 update, gateway won't come up. Doctor after `doctor --fix` says:
```
Failed to read config at /home/scotter/.openclaw/openclaw.json Error: Cannot find module 'grammy'
Require stack:
- /home/scotter/.local/share/pnpm/global/5/.pnpm/openclaw@2026.4.21_@napi-rs+canvas@0.1.97/node_modules/openclaw/dist/extensions/telegram/allowed-updates-BD2bJyzD.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at Function.resolve (node:internal/modules/helpers:157:19)
    at jitiResolve (/home/scotter/.local/share/pnpm/global/5/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:148703)
    at jitiRequire (/home/scotter/.local/share/pnpm/global/5/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:150290)
    at /home/scotter/.local/share/pnpm/global/5/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:157987
    at /home/scotter/.local/share/pnpm/global/5/.pnpm/openclaw@2026.4.21_@napi-rs+canvas@0.1.97/node_modules/openclaw/dist/extensions/telegram/allowed-updates-BD2bJyzD.js:1:245
    at eval_evalModule (/home/scotter/.local/share/pnpm/global/5/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:155533)
    at jitiRequire (/home/scotter/.local/share/pnpm/global/5/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:150967)
    at /home/scotter/.local/share/pnpm/global/5/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:157987
    at /home/scotter/.local/share/pnpm/global/5/.pnpm/openclaw@2026.4.21_@napi-rs+canvas@0.1.97/node_modules/openclaw/dist/extensions/telegram/probe-CMHHfwas.js:6:31 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/scotter/.local/share/pnpm/global/5/.pnpm/openclaw@2026.4.21_@napi-rs+canvas@0.1.97/node_modules/openclaw/dist/extensions/telegram/allowed-updates-BD2bJyzD.js'
  ]
}

Invalid config:
- <root>: read failed: Error: Cannot find module 'grammy'
Require stack:
- /home/scotter/.local/share/pnpm/global/5/.pnpm/openclaw@2026.4.21_@napi-rs+canvas@0.1.97/node_modules/openclaw/dist/extensions/telegram/allowed-updates-BD2bJyzD.js
```

### Steps to reproduce

See summary.

### Expected behavior

See summary.

### Actual behavior

See summary.

### OpenClaw version

2026.4.21

### Operating system

Linux Mint, latest

### Install method

bash `openclaw update`

### Model

gpt 5.4

### Provider / routing chain

openrouter

### Additional provider/model setup details

_No response_

### Logs, screenshots, and evidence

```shell

```

### Impact and severity

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by acartine**
Fixes #70137 (also tracked as #69831).

## Problem

After upgrading to v2026.4.21, the gateway crash-loops on startup with:

```
Config invalid
File: ~/.openclaw/openclaw.json
Problem:
  - <root>: read failed: Error: Cannot find module 'grammy'
Require stack:
- .../dist/extensions/telegram/allowed-updates-*.js
```

## Root cause

`extensions/telegram/package.json` declares `"grammy": "^1.42.0"`, but the version actually present at install time is `1.41.1`. `scripts/stage-bundled-plugin-runtime-deps.mjs` calls `dependencyVersionSatisfied(spec, installedVersion)` before staging — the `^1.42.0` range is not satisfied by `1.41.1`, so `grammy` is silently skipped and never copied into `dist/extensions/telegram/node_modules/`. At runtime the telegram extension fails to require it.

## Fix

Change the spec to `^1.41.0` so it matches the installed version. One-line, single-file diff. Verified locally — gateway boots clean and Telegram channel comes up.

## Why a separate PR

PR #70091 already proposes the same one-line change but bundles 9 unrelated cherry-picks (~595 additions across 21 files) plus two open Greptile review findings, which will slow it down. This regression is breaking every install on v2026.4.21, so a minimal targeted fix seems worth the duplication. Happy to close this if #70091's grammy commit can be cherry-picked separately.

### CODE REVIEW

**Comment by acartine** [comment]
Withdrawing — my diagnosis was wrong. The version spec isn't the actual root cause.
