### ISSUE TITLE
[Bug]: Feishu channel fails to dispatch messages after upgrading from v2026.4.5 to v2026.4.24 — createScopedPairingAccess is not a function

### ISSUE THREAD

**Issue by 8Sign24** [clawdbot/clawdbot#71981]
## Bug Description

After upgrading OpenClaw from v2026.4.5 to v2026.4.24, the Feishu channel fails to dispatch any messages. Both private messages (DM) and group messages are received but cannot be replied to.

## Error Message

```
feishu[default]: failed to dispatch message: TypeError: (0 , _feishu.createScopedPairingAccess) is not a function
```

## Root Cause Analysis

The `@openclaw/feishu` plugin (v2026.3.13, latest on npm) imports `createScopedPairingAccess` from `openclaw/plugin-sdk/feishu`:

```typescript
// In feishu plugin's bot.ts
import {
  createScopedPairingAccess,
  // ...other imports
} from "openclaw/plugin-sdk/feishu";
```

However, OpenClaw v2026.4.24's SDK (`feishu.d.ts`) only exports `createChannelPairingController` but NOT `createScopedPairingAccess`:

```typescript
// feishu.d.ts exports:
export { createChannelPairingController } from "./channel-pairing.js";
// createScopedPairingAccess is NOT exported here
```

The `createScopedPairingAccess` function exists in the core (`channel-pairing-DF6gWII4.js`) but is not re-exported through the feishu SDK barrel module.

## Environment

- OpenClaw version: 2026.4.24
- Previous version: 2026.4.5
- @openclaw/feishu version: 2026.3.13 (latest on npm)
- OS: Ubuntu 24.04
- Node.js: v24.14.0
- Install method: npm install -g openclaw

## Steps to Reproduce

1. Install OpenClaw v2026.4.24 via npm
2. Configure Feishu channel with WebSocket mode
3. Send a message to the bot (DM or group)
4. Observe that messages are received but dispatch fails with the error above

## Expected Behavior

Feishu channel should be able to dispatch messages normally after upgrade.

## Additional Context

- The `createChannelPairingController` function has the same signature as `createScopedPairingAccess` and returns a compatible type (it extends `ScopedPairingAccess`), suggesting it could be used as a drop-in replacement
- This appears to be a version mismatch between OpenClaw core and the feishu plugin SDK interface
- Related issues: #71802 (plugin-sdk issues in 2026.4.24), #71977 (Feishu streaming issues)

## Suggested Fix

Either:
1. Export `createScopedPairingAccess` from `feishu.d.ts` in the SDK
2. Or update `@openclaw/feishu` plugin to use `createChannelPairingController` instead
3. Ensure SDK interface compatibility between core and channel plugins during releases

**Comment by steipete** [comment]
Thanks for the detailed report. I checked this against current main, the package metadata, and the SDK contract.

This is not a host-side SDK regression we want to preserve compatibility for. The failing import comes from the stale npm package `@openclaw/feishu@2026.3.13`, which predates the March 19 SDK refactor that removed `createScopedPairingAccess` from the private `openclaw/plugin-sdk/feishu` helper surface.

Current Feishu in main is already on the new path:

- `extensions/feishu/src/bot.ts` imports `createChannelPairingController` from `openclaw/plugin-sdk/channel-pairing`
- `extensions/feishu/package.json` requires OpenClaw `>=2026.4.25`
- `docs/channels/feishu.md` documents OpenClaw `2026.4.25` or newer
- `docs/plugins/sdk-overview.md` documents channel-branded helper seams such as `plugin-sdk/feishu` as bundled-plugin maintenance surfaces, not stable third-party import paths

So the actionable fix is to use/publish the Feishu plugin version that matches the 2026.4.25 host contract, not to restore the old `createScopedPairingAccess` export in `plugin-sdk/feishu`. Closing this as not planned for backwards compatibility.
