### PR TITLE
fix: prune stale dist chunks after npm upgrades

### LINKED ISSUE #66752: [Bug]: ERR_MODULE_NOT_FOUND audit-Cb4RZuLD.js on ARM64 npm global install (v2026.4.14)
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary
After upgrading from 2026.4.10 to 2026.4.14 via `npm install -g openclaw@2026.4.14` on Raspberry Pi (ARM64), the CLI fails with `ERR_MODULE_NOT_FOUND` when running `openclaw channels status --probe`. The issue persists after complete uninstall + reinstall with cache clearing.

### Steps to reproduce

1. On Raspberry Pi 4/5 running 64-bit OS (Linux 6.8.0-1051-raspi arm64)
2. Node v22.22.2
3. `npm install -g openclaw@2026.4.14`
4. `openclaw channels status --probe`

### Expected behavior

Gateway reachable, Discord channel status displays correctly.

### Actual behavior

Gateway not reachable: GatewayClientRequestError: Error: Cannot find module '/home/user/.npm-global/lib/node_modules/openclaw/dist/audit-Cb4RZuLD.js' imported from /home/user/.npm-global/lib/node_modules/openclaw/dist/channel-CJUAgRQR.js: code=ERR_MODULE_NOT_FOUND

### OpenClaw version

2026.4.14

### Operating system

Ubuntu Server 24.04 LTS headless

### Install method

_No response_

### Model

N/A

### Provider / routing chain

N/A

### Additional provider/model setup details

_No response_

### Logs, screenshots, and evidence

```shell

```

### Impact and severity

_No response_

### Investigation findings
- The file `audit-Cb4RZuLD.js` does not exist in the `dist/` directory after installation
- However, other `audit-*.js` files with different hashes are present (e.g., `audit-B_sDQNwU.js`, `audit-BmD9jIMx.js`)
- Clean reinstall doesn't solve the problem
- This suggests a build artifact mismatch where `channel-CJUAgRQR.js` imports a stale chunk hash
- Rolling back to `2026.4.10` completely resolves the issue

### Environment
- **OpenClaw version:** 2026.4.14 (323493f)
- **OS:** Linux 6.8.0-1051-raspi (arm64) on Raspberry Pi
- **Node:** v22.22.2
- **Install method:** npm global (`/home/user/.npm-global/`)

### Related
This appears similar to the root cause fixed in PR #65471 (respawn plugin refresh after self-update). However, that fix may not cover the npm global install path or may have regressed on ARM64 builds.

### Workaround
Downgrade to 2026.4.10: `npm install -g openclaw@2026.4.10`

### Logs / Evidence
$ ls -la /home/user/.npm-global/lib/node_modules/openclaw/dist/ | grep audit

Shows multiple audit-*.js files but audit-Cb4RZuLD.js is missing
$ openclaw channels status --probe

Fails with ERR_MODULE_NOT_FOUND

### PR DESCRIPTION
**Pull request by obviyus**
Fixes #66752

## Summary
- add a packaged dist inventory for global-install verification
- prune stale dist files from installed packages during postinstall
- cover the inventory + prune paths with focused tests

## Verification
- `pnpm test src/infra/package-dist-inventory.test.ts src/infra/update-global.test.ts src/infra/update-runner.test.ts src/cli/update-cli.test.ts test/scripts/postinstall-bundled-plugins.test.ts`
- `OPENCLAW_PREPACK_PREPARED=1 npm pack`
- installed tarball in a temp npm prefix and verified stale `audit-Cb4RZuLD.js` / `channel-CJUAgRQR.js` get pruned from the installed package

### CODE REVIEW

**Comment by obviyus** [comment]
@greptile-apps review please

**Comment by obviyus** [comment]
Verification run on this branch:

- `OPENCLAW_LOCAL_CHECK=0 pnpm test test/scripts/postinstall-bundled-plugins.test.ts src/infra/package-dist-inventory.test.ts src/infra/update-global.test.ts src/infra/update-runner.test.ts src/cli/update-cli.test.ts`
- `pnpm build`
- tarball / npm smoke:
  - fresh install old release
  - fresh install patched tarball
  - direct npm upgrade old -> patched tarball
  - direct npm downgrade patched tarball -> old
  - `openclaw update` old -> patched tarball in isolated prefix
- postinstall prune check on installed package tree with injected stale dist chunks
- rebase / follow-up fix checks:
  - `pnpm tsgo`
  - `OPENCLAW_LOCAL_CHECK=0 pnpm test src/infra/package-dist-inventory.test.ts src/infra/update-global.test.ts test/scripts/build-all.test.ts`

**Comment by obviyus** [comment]
Landed.

- Source commit: [`da59768ff71705a1374d693ce6f41c7d883db900`](https://github.com/openclaw/openclaw/commit/da59768ff71705a1374d693ce6f41c7d883db900)
- Merge commit: [`94d5c3dd6bde5b8079ecd5093271f6192580d5b0`](https://github.com/openclaw/openclaw/commit/94d5c3dd6bde5b8079ecd5093271f6192580d5b0)
