### ISSUE TITLE
[Bug]: ERR_MODULE_NOT_FOUND audit-Cb4RZuLD.js on ARM64 npm global install (v2026.4.14)

### ISSUE THREAD

**Issue by dongkl** [clawdbot/clawdbot#66752]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary
After upgrading from 2026.4.10 to 2026.4.14 via `npm install -g openclaw@2026.4.14` on Raspberry Pi (ARM64), the CLI fails with `ERR_MODULE_NOT_FOUND` when running `openclaw channels status --probe`. The issue persists after complete uninstall + reinstall with cache clearing.

### Steps to reproduce

1. On Raspberry Pi 4/5 running 64-bit OS (Linux 6.8.0-1051-raspi arm64)
2. Node v22.22.2
3. `npm install -g openclaw@2026.4.14`
4. `openclaw channels status --probe`

### Expected behavior

Gateway reachable, Discord channel status displays correctly.

### Actual behavior

Gateway not reachable: GatewayClientRequestError: Error: Cannot find module '/home/user/.npm-global/lib/node_modules/openclaw/dist/audit-Cb4RZuLD.js' imported from /home/user/.npm-global/lib/node_modules/openclaw/dist/channel-CJUAgRQR.js: code=ERR_MODULE_NOT_FOUND

### OpenClaw version

2026.4.14

### Operating system

Ubuntu Server 24.04 LTS headless

### Model

N/A

### Provider / routing chain

N/A

### Logs, screenshots, and evidence

```shell

```

### Investigation findings
- The file `audit-Cb4RZuLD.js` does not exist in the `dist/` directory after installation
- However, other `audit-*.js` files with different hashes are present (e.g., `audit-B_sDQNwU.js`, `audit-BmD9jIMx.js`)
- Clean reinstall doesn't solve the problem
- This suggests a build artifact mismatch where `channel-CJUAgRQR.js` imports a stale chunk hash
- Rolling back to `2026.4.10` completely resolves the issue

### Environment
- **OpenClaw version:** 2026.4.14 (323493f)
- **OS:** Linux 6.8.0-1051-raspi (arm64) on Raspberry Pi
- **Node:** v22.22.2
- **Install method:** npm global (`/home/user/.npm-global/`)

### Related
This appears similar to the root cause fixed in PR #65471 (respawn plugin refresh after self-update). However, that fix may not cover the npm global install path or may have regressed on ARM64 builds.

### Workaround
Downgrade to 2026.4.10: `npm install -g openclaw@2026.4.10`

### Logs / Evidence
$ ls -la /home/user/.npm-global/lib/node_modules/openclaw/dist/ | grep audit

Shows multiple audit-*.js files but audit-Cb4RZuLD.js is missing
$ openclaw channels status --probe

Fails with ERR_MODULE_NOT_FOUND
