### ISSUE TITLE
[Bug]: Feishu channel fails to start with "Cannot find module openclaw/plugin-sdk/text-runtime" in 2026.4.22

### ISSUE THREAD

**Issue by ASNFalcon** [clawdbot/clawdbot#70683]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After upgrading from 2026.4.15 to 2026.4.22, both Feishu channel accounts immediately exit on startup with Cannot find
   module openclaw/plugin-sdk/text-runtime and enter a permanent auto-restart loop.

### Steps to reproduce

 1. Deploy ghcr.io/openclaw/openclaw:2026.4.22 with at least one Feishu account configured in channels.feishu.
  2. Start the gateway.
  3. Observe the Feishu channel process exiting within ~30 seconds of starting channels and sidecars....

### Expected behavior

 In 2026.4.15, Feishu channels start normally and establish WebSocket connections with no module errors.

### Actual behavior

  Both Feishu accounts (main, muse) immediately exit and auto-restart up to 10 times before giving up, with the
  following error on each attempt:
  [feishu] [main] channel exited: Cannot find module
  '/home/node/.openclaw/plugin-runtime-deps/openclaw-2026.4.22-f53b52ad6d21/node_modules/openclaw/plugin-sdk/text-runtim
  e'
  imported from
  '/home/node/.openclaw/plugin-runtime-deps/openclaw-2026.4.22-f53b52ad6d21/dist/extensions/feishu/conversation-id-DWS3E
  p2A.js'
  Did you mean to import "openclaw/plugin-sdk/text-runtime.js"?

### OpenClaw version

 2026.4.22 (regresses from 2026.4.15)

### Operating system

 Linux (Kubernetes, Node.js 24.14.0)

### Install method

 Docker / Kubernetes

### Model

openrouter/qwen/qwen3.6-plus

### Provider / routing chain

 openclaw -> openrouter -> qwen

### Logs, screenshots, and evidence

```shell
2026-04-24T00:13:25.531+08:00 [feishu] [main] channel exited: Cannot find module
    '/home/node/.openclaw/plugin-runtime-deps/openclaw-2026.4.22-f53b52ad6d21/node_modules/openclaw/plugin-sdk/text-runt
  ime'
    imported from
    '/home/node/.openclaw/plugin-runtime-deps/openclaw-2026.4.22-f53b52ad6d21/dist/extensions/feishu/conversation-id-DWS
  3Ep2A.js'
    Did you mean to import "openclaw/plugin-sdk/text-runtime.js"?
  2026-04-24T00:13:25.534+08:00 [feishu] [main] auto-restart attempt 1/10 in 5s
  2026-04-24T00:13:25.536+08:00 [feishu] [muse] auto-restart attempt 1/10 in 5s

  The feishu extension bundle imports openclaw/plugin-sdk/text-runtime without .js. The extracted plugin-runtime-deps
  package.json has "./plugin-sdk/*": "./plugin-sdk/*.js" in exports, but Node.js 24 fails to resolve it. The file
  text-runtime.js exists in the image at /app/dist/extensions/node_modules/openclaw/plugin-sdk/text-runtime.js but is
  not accessible from the plugin subprocess context.
```

### Impact and severity

 - Affected: all users with Feishu channels on 2026.4.22
  - Severity: High — Feishu is completely non-functional, no messages can be received or sent
  - Frequency: 100% reproducible on every startup
  - Consequence: Full loss of Feishu channel functionality

### Additional information

Last known good: 2026.4.15. First known bad: 2026.4.22 (2026.4.18–2026.4.21 not tested). Workaround: roll back to
  2026.4.15.

**Comment by steipete** [comment]
This is fixed on main by 645294510c5e179cde50a104b58694a261ced629 (`fix: restore bundled plugin SDK alias`).

Evidence:
- the loader now creates an `extensions/node_modules/openclaw` alias package for staged bundled plugin runtime roots and maps `./plugin-sdk/*` to wrapper files, including extensionless imports such as `openclaw/plugin-sdk/text-runtime`: src/plugins/loader.ts:602 and src/plugins/loader.ts:676.
- the package export for `./plugin-sdk/text-runtime` exists: package.json:300.
- regression coverage loads a packaged/staged bundled plugin that imports `openclaw/plugin-sdk/text-runtime` without `.js`: src/plugins/loader.test.ts:1457 and src/plugins/loader.test.ts:1561.
- the active changelog calls out restoring bundled plugin `openclaw/plugin-sdk/*` resolution from packaged installs and external runtime-deps stage roots: CHANGELOG.md:11.

Closing as fixed on main. This will still reproduce on the already-published 2026.4.22 image; use a build containing 645294510c or newer.
