### ISSUE TITLE
[Bug]: @openclaw/discord@2026.3.13 fails on openclaw@2026.4.26: missing plugin-sdk/discord export

### ISSUE THREAD

**Issue by rderickson9** [clawdbot/clawdbot#73685]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After upgrading OpenClaw core from `2026.4.25` to `2026.4.26`, the external Discord plugin fails to load during gateway startup.

`@openclaw/discord@2026.3.13` imports `openclaw/plugin-sdk/discord`, but `openclaw@2026.4.26` no longer exports `./plugin-sdk/discord` in its package exports map. The plugin loader then tries to resolve:

`/usr/local/lib/node_modules/openclaw/dist/plugin-sdk/root-alias.cjs/discord`

That path does not exist, so the Discord plugin never registers and the bot appears offline.

Force reinstalling the plugin does not help because npm still publishes `@openclaw/discord@2026.3.13` as latest, with the same import. Rolling core back to `openclaw@2026.4.25` restores Discord.

## Steps to reproduce

1. On macOS, install/run `openclaw@2026.4.25` with the Discord plugin enabled.
2. Install the Discord plugin:

   
bash
   openclaw plugins install @openclaw/discord
   
3. Confirm Discord works on `2026.4.25`.
4. Upgrade core:

   
bash
   openclaw update
   This upgrades core to `openclaw@2026.4.26`.

5. Restart the gateway:

   
bash
   openclaw gateway restart
   
6. Check logs/status:

   
bash
   openclaw logs --follow
   openclaw status --deep

### Expected behavior

# Expected behavior

The Discord plugin should load successfully after upgrading core, and the Discord bot should come online as it did on `openclaw@2026.4.25`.

## Actual behavior

The Discord plugin fails to load during gateway startup, so the bot stays offline.

Error:
text
[plugins] discord failed to load from ~/.openclaw/extensions/discord/index.ts:
Error: Cannot find module
'/usr/local/lib/node_modules/openclaw/dist/plugin-sdk/root-alias.cjs/discord'
`@openclaw/discord@2026.3.13` imports `openclaw/plugin-sdk/discord`, but `openclaw@2026.4.26` does not export `./plugin-sdk/discord`.

A force reinstall does not fix it:
bash
openclaw plugins install @openclaw/discord --force
because npm still resolves `@openclaw/discord` to `2026.3.13`.

## Workaround

Rollback core to `openclaw@2026.4.25`.

### OpenClaw version

openclaw@2026.4.26

### Operating system

macos 15.4

### Install method

NPM global

### Model

gpt 5.5

### Provider / routing chain

openclaw -> gateway> gpt

### Logs, screenshots, and evidence

```shell

```

**Comment by steipete** [comment]
Fixed on `main` in `3cad579c4e` (`fix(plugin-sdk): restore discord compatibility facade`).

What landed:
- Restored `openclaw/plugin-sdk/discord` as a deprecated compatibility facade for the published `@openclaw/discord@2026.3.13` package.
- Covered the actual package imports: config/account/directory/status helpers plus Discord thread-binding helpers.
- Restored the legacy `plugin-sdk/compat` group-policy warning export that the same package imports after the Discord subpath resolves.
- Verified by unpacking `@openclaw/discord@2026.3.13` against the built checkout: it imports, registers the `discord` channel, installs 3 hooks, and exposes config/schema.
- Testbox validation passed: `pnpm build` and `pnpm check:changed`.

Closing as completed.

**Comment by steipete** [comment]
Ignore above messgage. What external Discord plugin? We ship that internally. Refactor was a cleanup. No external plugin is supposed to use an discord specific API that was a leftover from not finished plugin API work.

**Comment by obahareth** [comment]
I had the same issue, `dist/extensions/discord` was missing from the homebrew (or linuxbrew in my case) installation and I restored it from the npm tarball and all worked for me.

It disappears every time I do a brew upgrade.
