### ISSUE TITLE
[Bug] exec commands receive SIGKILL frequently (every conversation turn)

### ISSUE THREAD

**Issue by xunx33** [clawdbot/clawdbot#66359]
## Bug Description

After upgrading to 2026.4.12, long-running exec commands are frequently terminated with SIGKILL. The issue is **not** triggered on every conversation turn — it occurs after executing a task that takes longer than usual (e.g., compound exec commands, multi-step operations, or running the openclaw CLI).

## Actual System Messages

After a long-running task completes, subsequent exec commands fail with SIGKILL and these system messages appear repeatedly:

`
System (untrusted): [2026-04-14 12:56:32 GMT+8] Exec failed (oceanic-, signal SIGKILL)
System (untrusted): [2026-04-14 12:56:51 GMT+8] Exec failed (brisk-sl, signal SIGKILL) :: error: too many arguments for 'sessions'. Expected 0 arguments but got 1.
System (untrusted): [2026-04-14 12:57:10 GMT+8] Exec failed (marine-c, signal SIGKILL)
System (untrusted): [2026-04-14 12:57:29 GMT+8] Exec failed (good-mea, signal SIGKILL)
`

Note on the second entry: the command attempted was openclaw sessions list which returns an error 	oo many arguments for 'sessions'. Expected 0 arguments but got 1. — indicating that in 2026.4.12, the sessions subcommand no longer accepts list as a valid argument. This appears to be a CLI breaking change as well.

These system error messages appear in the conversation and are noisy. However, final output is still delivered correctly despite SIGKILL.

## Expected Behavior

- Exec commands should complete or timeout gracefully without SIGKILL
- No system error messages should appear for normal command execution
- The sessions CLI command should work as expected (list subcommand should be valid)

## Steps to Reproduce

1. Execute a compound or long-running exec command
2. After that task completes, try running another exec command (e.g., openclaw status, openclaw sessions list)
3. The subsequent command gets SIGKilled before completion
4. System error messages appear in the conversation

## Environment

- Version: 2026.4.12 (1c0672b)
- OS: Windows 11 x64
- Node: v24.14.0
- Shell: PowerShell

## Additional Context

- Final output is still delivered correctly despite SIGKILL (not a silent failure)
- The issue is consistent on Windows platform after long tasks
- The error messages clutter the conversation but do not affect functionality
- There also appears to be a breaking CLI change in the sessions subcommand (no longer accepts list)

**Comment by steipete** [comment]
Closing this as implemented after Codex review.

Current `main` already contains an explicit Windows exec wait-settle fix for the reported SIGKILL symptom, with regression coverage, and the separate `openclaw sessions list` complaint is unsupported CLI syntax on current main/docs.

What I checked:

- **Release note documents the Windows exec fix:** The shipped changelog explicitly says Windows exec now settles supervisor waits from child exit state after stdout/stderr drain even when `close` never arrives, preventing forced SIGKILL on Windows. ([`CHANGELOG.md:1096`](https://github.com/openclaw/openclaw/blob/9a0b26cafca7/CHANGELOG.md#L1096), [9a0b26cafca7](https://github.com/openclaw/openclaw/commit/9a0b26cafca7))
- **Current supervisor code implements Windows exit-state settle:** `createChildAdapter` now stores child exit state and settles once stdout/stderr drain on Windows via `maybeSettleAfterWindowsExit()` and `scheduleWindowsCloseFallback()`. ([`src/process/supervisor/adapters/child.ts:204`](https://github.com/openclaw/openclaw/blob/9a0b26cafca7/src/process/supervisor/adapters/child.ts#L204), [9a0b26cafca7](https://github.com/openclaw/openclaw/commit/9a0b26cafca7))
- **Regression test covers missing `close` on Windows:** The test asserts that Windows waits resolve from `exit` plus drained stdio even when `close` never arrives. ([`src/process/supervisor/adapters/child.test.ts:175`](https://github.com/openclaw/openclaw/blob/9a0b26cafca7/src/process/supervisor/adapters/child.test.ts#L175), [9a0b26cafca7](https://github.com/openclaw/openclaw/commit/9a0b26cafca7))
- **Latest release still ships the fix:** The latest tagged release `v2026.4.23` contains the same Windows wait-settle code path in the supervisor adapter. ([`src/process/supervisor/adapters/child.ts:204`](https://github.com/openclaw/openclaw/blob/a9797214338b/src/process/supervisor/adapters/child.ts#L204), [a9797214338b](https://github.com/openclaw/openclaw/commit/a9797214338b))
- **`sessions list` is not a supported CLI subcommand on current main:** The CLI defines `openclaw sessions` as the listing command, with `cleanup` as the subcommand; the docs page likewise shows `openclaw sessions` examples and no `list` subcommand. ([`src/cli/program/register.status-health-sessions.ts:124`](https://github.com/openclaw/openclaw/blob/9a0b26cafca7/src/cli/program/register.status-health-sessions.ts#L124), [9a0b26cafca7](https://github.com/openclaw/openclaw/commit/9a0b26cafca7))
- **Docs confirm `openclaw sessions` usage:** The public Sessions CLI docs mirror the current command shape and show `openclaw sessions` / `openclaw sessions --json` usage, not `openclaw sessions list`. Public docs: [`docs/cli/sessions.md`](https://docs.openclaw.ai/cli/sessions). ([`docs/cli/sessions.md:8`](https://docs.openclaw.ai/cli/sessions), [9a0b26cafca7](https://github.com/openclaw/openclaw/commit/9a0b26cafca7))

So I’m closing this as already implemented rather than keeping a duplicate issue open.

Review notes: reviewed against [9a0b26cafca7](https://github.com/openclaw/openclaw/commit/9a0b26cafca76d267dd231b5eaceadb071ec749d).
