### PR TITLE
fix(plugin-sdk): add missing discord export for external channel plugin

### LINKED ISSUE #73685: [Bug]: @openclaw/discord@2026.3.13 fails on openclaw@2026.4.26: missing plugin-sdk/discord export
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After upgrading OpenClaw core from `2026.4.25` to `2026.4.26`, the external Discord plugin fails to load during gateway startup.

`@openclaw/discord@2026.3.13` imports `openclaw/plugin-sdk/discord`, but `openclaw@2026.4.26` no longer exports `./plugin-sdk/discord` in its package exports map. The plugin loader then tries to resolve:

`/usr/local/lib/node_modules/openclaw/dist/plugin-sdk/root-alias.cjs/discord`

That path does not exist, so the Discord plugin never registers and the bot appears offline.

Force reinstalling the plugin does not help because npm still publishes `@openclaw/discord@2026.3.13` as latest, with the same import. Rolling core back to `openclaw@2026.4.25` restores Discord.

## Steps to reproduce

1. On macOS, install/run `openclaw@2026.4.25` with the Discord plugin enabled.
2. Install the Discord plugin:

   
bash
   openclaw plugins install @openclaw/discord
   
3. Confirm Discord works on `2026.4.25`.
4. Upgrade core:

   
bash
   openclaw update
   This upgrades core to `openclaw@2026.4.26`.

5. Restart the gateway:

   
bash
   openclaw gateway restart
   
6. Check logs/status:

   
bash
   openclaw logs --follow
   openclaw status --deep

### Expected behavior

# Expected behavior

The Discord plugin should load successfully after upgrading core, and the Discord bot should come online as it did on `openclaw@2026.4.25`.

## Actual behavior

The Discord plugin fails to load during gateway startup, so the bot stays offline.

Error:
text
[plugins] discord failed to load from ~/.openclaw/extensions/discord/index.ts:
Error: Cannot find module
'/usr/local/lib/node_modules/openclaw/dist/plugin-sdk/root-alias.cjs/discord'
`@openclaw/discord@2026.3.13` imports `openclaw/plugin-sdk/discord`, but `openclaw@2026.4.26` does not export `./plugin-sdk/discord`.

A force reinstall does not fix it:
bash
openclaw plugins install @openclaw/discord --force
because npm still resolves `@openclaw/discord` to `2026.3.13`.

## Workaround

Rollback core to `openclaw@2026.4.25`.

### OpenClaw version

openclaw@2026.4.26

### Operating system

macos 15.4

### Install method

NPM global

### Model

gpt 5.5

### Provider / routing chain

openclaw -> gateway> gpt

### Additional provider/model setup details

_No response_

### Logs, screenshots, and evidence

```shell

```

### Impact and severity

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SymbolStar**
## Summary

Add `./plugin-sdk/discord` to the package.json exports map so `@openclaw/discord@2026.3.13` (and future versions) can resolve `openclaw/plugin-sdk/discord`.

## Root cause

`openclaw@2026.4.26`'s `package.json` `exports` map does not include `./plugin-sdk/discord`. When the external Discord plugin does `import { emptyPluginConfigSchema } from "openclaw/plugin-sdk/discord"`, Node's exports-map resolver rejects it. The plugin loader's fallback tries `dist/plugin-sdk/root-alias.cjs/discord` which doesn't exist either, so the Discord plugin never registers and the bot stays offline.

## Changes

1. **`src/plugin-sdk/discord.ts`** — new barrel re-exporting the four symbols the Discord plugin uses: `OpenClawPluginApi`, `OpenClawConfig`, `PluginRuntime`, `emptyPluginConfigSchema`.
2. **`package.json`** — add `./plugin-sdk/discord` export entry pointing to the new barrel's build output.
3. **`scripts/lib/plugin-sdk-entrypoints.json`** — register `discord` so the build pipeline includes it.

## Verification

All source imports resolve to existing files. Build output (`dist/plugin-sdk/discord.js` + `.d.ts`) will be produced by the standard plugin-sdk build pipeline.

Fixes #73685

### CODE REVIEW

**Comment by steipete** [comment]
Dependency check update: keep this PR open, but the current four-symbol shim is not enough for the latest published external Discord package I verified.

I unpacked @openclaw/discord@2026.3.13 and it imports `openclaw/plugin-sdk/discord` from multiple files. Besides `OpenClawPluginApi`, `PluginRuntime`, and `emptyPluginConfigSchema`, it also imports Discord-specific runtime/config helpers such as `buildChannelConfigSchema`, `DiscordConfigSchema`, `getChatChannelMeta`, `resolveDiscordAccount`, directory config helpers, group policy/status helpers, and thread-binding helpers including `autoBindSpawnedDiscordSubagent`, `listThreadBindingsBySessionKey`, and `unbindThreadBindingsBySessionKey`.

So the safe path is either a complete compatibility shim matching that external package surface, or publishing/updating the external package so it no longer depends on the removed barrel. I did not land the partial shim.

**Comment by steipete** [comment]
Thanks @SymbolStar. I landed the compatibility fix on `main` in `3cad579c4e` (`fix(plugin-sdk): restore discord compatibility facade`).

I kept your package-export direction, but made the shim match the actual published `@openclaw/discord@2026.3.13` import surface. The four-symbol version here would still fail after resolving the subpath because the package also imports Discord config/account/directory/status helpers, thread-binding helpers, and then a legacy `plugin-sdk/compat` group-policy warning helper.

Validation on the landed commit:
- unpacked `@openclaw/discord@2026.3.13` against the built checkout; it imports, registers `discord`, installs 3 hooks, and exposes config/schema
- `pnpm build` passed in Testbox
- `pnpm check:changed` passed in Testbox

Closing this PR as superseded by the fuller landed fix.
