### ISSUE TITLE
[Bug]: Regression: Telegram provider fails on Windows after 2026.4.23 (deleteWebhook / setMyCommands errors)

### ISSUE THREAD

**Issue by trentwolfchester** [clawdbot/clawdbot#74086]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After upgrading OpenClaw from 2026.4.23 to any newer version (2026.4.24+), the Telegram provider fails to initialise correctly on Windows. The gateway starts and reaches ready, but Telegram repeatedly fails webhook cleanup and command sync with network request errors.

Rolling back to 2026.4.23 restores full functionality with no configuration changes.

This appears to be a regression introduced in 2026.4.24, likely related to changes in the HTTP/runtime layer (undici/grammY or bundled plugin/runtime dependencies).

[powershell_log.txt](https://github.com/user-attachments/files/27189621/powershell_log.txt)
[openclaw-diagnostics-2026-04-29T04-53-50-045Z-18996.zip](https://github.com/user-attachments/files/27189620/openclaw-diagnostics-2026-04-29T04-53-50-045Z-18996.zip)

### Steps to reproduce

Install OpenClaw globally via npm:

npm install -g openclaw
Configure a Telegram bot in openclaw.json (working config).

Run on Windows:

openclaw gateway
Observe behaviour on different versions:
2026.4.23 → works
2026.4.24+ → fails

### Expected behavior

Install OpenClaw globally via npm:

npm install -g openclaw
Configure a Telegram bot in openclaw.json (working config).

Run on Windows:

openclaw gateway
Observe behaviour on different versions:
2026.4.23 → works
2026.4.24+ → fails

### Actual behavior

On 2026.4.24+, the gateway starts but Telegram provider fails repeatedly:

telegram deleteWebhook failed: Network request for 'deleteWebhook' failed!
Telegram webhook cleanup failed
telegram deleteMyCommands failed
telegram setMyCommands failed
Telegram command sync failed: HttpError

Also observed:

Polling stall detected (no completed getUpdates...)
health-monitor restarting (reason: disconnected)

In some runs, an additional error appears:

Cannot find module ... dist\extensions\telegram\bot-native-commands.runtime-*.js

Despite this:

Direct API calls to api.telegram.org via PowerShell succeed (HTTP 200)
The same bot + config works perfectly on 2026.4.23

Telegram provider should:

Successfully clear webhook
Start polling
Sync commands
Remain connected

As it does in 2026.4.23.

### OpenClaw version

2026.4.26

### Operating system

Windows 11 Running on loopback (127.0.0.1) v22.19.0

### Install method

npm install -g openclaw

### Model

openai-codex

### Provider / routing chain

Running on loopback (127.0.0.1)

### Additional provider/model setup details

Issue persists after:
clearing sessions
deleting locks
manually clearing Telegram webhook
reinstalling OpenClaw
Bonjour plugin instability also observed in newer versions, but Telegram failure occurs independently
This does not appear to be a configuration issue

Diagnostics archive and logs attached.

[powershell_log.txt](https://github.com/user-attachments/files/27189687/powershell_log.txt)
[openclaw-diagnostics-2026-04-29T04-53-50-045Z-18996.zip](https://github.com/user-attachments/files/27189686/openclaw-diagnostics-2026-04-29T04-53-50-045Z-18996.zip)

### Logs, screenshots, and evidence

```shell

```

**Comment by trentwolfchester** [comment]
Tested 2026.4.27. It is improved but still not fixed on my Windows host.

The gateway now adds Telegram fetch fallback:
[telegram] fetch fallback: enabling sticky IPv4-only dispatcher
[telegram] fetch fallback: DNS-resolved IP unreachable; trying alternative Telegram API IP

But it still repeatedly fails:
[telegram] deleteWebhook failed: Network request for 'deleteWebhook' failed!
[telegram] webhook cleanup failed: Network request for 'deleteWebhook' failed!

Also, Bonjour still loads and causes event-loop delay unless disabled:
[plugins] bonjour: service stuck in probing/unannounced
[diagnostic] liveness warning: event_loop_delay/event_loop_utilization

So 2026.4.27 is better, but Telegram still does not reliably initialise on Windows.
