### ISSUE TITLE
Bundled-plugin stageRuntimeDependencies fails under ProtectSystem=strict (EROFS; gateway can't write /usr/lib)

### ISSUE THREAD

**Issue by fawadafr** [clawdbot/clawdbot#69923]
## Environment

- OpenClaw 2026.4.20 (also reproduced on 2026.4.15)
- Installed via `npm i -g openclaw@latest` to `/usr/lib/node_modules/openclaw/`
- Running under systemd with hardened unit:
  - `ProtectSystem=strict`
  - `ProtectHome=read-only`
  - `NoNewPrivileges=yes`
  - `ReadWritePaths=/mnt/data/.openclaw /home/openclaw/.openclaw /tmp …` (narrow allowlist; `/usr/lib/` excluded)

## Symptom

After `openclaw update --yes --no-restart --json`:

```json
{
  "status": "error",
  "reason": "openclaw doctor",
  "steps": [
    { "name": "global update",    "exitCode": 0, "stdoutTail": "changed 454 packages in 36s" },
    { "name": "openclaw doctor",  "exitCode": 1,
      "stderrTail": "Error: Cannot find module '@slack/web-api'\nRequire stack:\n- /usr/lib/node_modules/openclaw/dist/extensions/slack/client-*.js" }
  ]
}
```

No `node_modules/` directory exists in any `/usr/lib/node_modules/openclaw/dist/extensions/*/`. All 15 bundled plugins that declare `"openclaw.bundle.stageRuntimeDependencies": true` (slack, discord, telegram, whatsapp, feishu, matrix, qqbot, nostr, webhooks, codex, google, diffs, acpx, amazon-bedrock, amazon-bedrock-mantle) have their deps missing.

## Root cause

The 2026.4.20 plugin-repair path (`src/plugins/loader.ts`, per release notes: *"install bundled runtime dependencies into each plugin's own runtime directory"*) attempts to write into `/usr/lib/node_modules/openclaw/dist/extensions/<id>/node_modules/`. Under `ProtectSystem=strict` that path is mounted read-only inside the service's mount namespace, and `NoNewPrivileges=yes` blocks any sudo escalation. The staging call fails with EROFS and is silently swallowed; subsequent plugin imports then fail module resolution and `openclaw doctor` crashes.

`openclaw doctor --fix` doesn't perform staging either — it imports plugins eagerly and crashes on the same missing module before any repair logic runs. There is no documented `openclaw plugins install-deps` or equivalent CLI.

## Related reports

- #61787 (open 2026-04-21) — npm global install of 2026.4.x silently omits channel plugin deps (exact match for our install method)
- #60004, #58922, #63043, #61363 — earlier reports of the same symptom under different plugin combinations

## Proposed fixes (in preference order)

1. **Env-overridable staging target.** Accept `OPENCLAW_PLUGIN_STAGE_DIR` (or `$STATE_DIRECTORY` from the systemd unit) so operators can point staging at a `ReadWritePaths`-included directory. Lets hardened hosts stage deps without loosening `ProtectSystem=strict` on the gateway unit.
2. **Explicit `openclaw plugins install-deps` CLI** that installs all bundled-plugin deps on demand, runnable from an out-of-namespace context (e.g., a systemd `ExecStartPre=` unit or update hook). Wrappers can call this instead of implementing custom staging logic.
3. **Document the incompatibility** between `stageRuntimeDependencies` and `ProtectSystem=strict` in `docs/install/` so operators know either to loosen hardening or pre-stage deps before enabling.

## Current workaround

Patched our update wrapper to run `npm install --ignore-scripts --no-fund --no-audit` as root in each bundled plugin dir that declares `stageRuntimeDependencies: true` and lacks `node_modules/`. Invoked in a recovery branch when `openclaw update` exits with `"reason": "openclaw doctor"` + `Cannot find module '@`, and unconditionally post-update (because `npm i -g openclaw@latest` wipes plugin `node_modules/` on every run, even on same-version reinstalls).

Happy to share the wrapper patch if it helps.

**Comment by kazuyuki-eguchi** [comment]
I hit what looks like the same underlying problem on a Raspberry Pi system with a global npm install.

Environment:
- OpenClaw 2026.4.20 (`115f05d`)
- host: Raspberry Pi / Linux ARM64
- install path under `/usr/lib/node_modules/openclaw`
- running OpenClaw as a non-root user (`tv-recorder`)

Observed behavior:
- after upgrading to 2026.4.20, `openclaw status` failed before normal CLI startup
- both bundled `discord` and `slack` plugins failed to load
- rollback restored normal behavior

The failure was:
- `PluginLoadFailureError: plugin load failed`
- `discord: failed to install bundled runtime deps`
- `slack: failed to install bundled runtime deps`
- npm tried to create:
  - `/usr/lib/node_modules/openclaw/dist/extensions/discord/node_modules`
  - `/usr/lib/node_modules/openclaw/dist/extensions/slack/node_modules`
- and failed with `EACCES: permission denied, mkdir ...`

Relevant log excerpt:

```text
[openclaw] Failed to start CLI: PluginLoadFailureError: plugin load failed: discord: failed to install bundled runtime deps: Error: npm error code EACCES
npm error syscall mkdir
npm error path /usr/lib/node_modules/openclaw/dist/extensions/discord/node_modules
...
slack: failed to install bundled runtime deps: Error: npm error code EACCES
npm error syscall mkdir
npm error path /usr/lib/node_modules/openclaw/dist/extensions/slack/node_modules
```

So in this case it is not just a read-only/ProtectSystem setup. A normal non-root runtime is still attempting to stage bundled plugin runtime dependencies under `/usr/lib/...`, which breaks CLI startup.

This seems to confirm that bundled runtime dependency staging should not depend on write access to the global install directory at runtime.

**Comment by benjaminluketucker** [comment]
MacOS repro from the Kai baseline, 2026.4.20

I hit the same bundled-runtime class from a clean local install path, but the unblock was different:
- `npm i -g @larksuiteoapi/node-sdk` restored `openclaw status --deep` on this host
- the saved successful run is now reproducible in the fresh bundle here:
  `/Users/max/clawd-main/artifacts/openclaw-upgrade-20260422-170456-retest/section1/status-deep-verified.txt`
- the bundle also captures the effective state/env provenance for the run

That suggests the Feishu bundle is hard-importing `@larksuiteoapi/node-sdk` and a missing declared dependency / staging gap still exists for clean installs on 2026.4.20+

If useful, I can paste the exact command/output pair that flipped the host from failing to passing.

**Comment by eminos** [comment]
My clanker put this together:

I’m seeing the same pattern on OpenClaw 2026.4.21 when running `openclaw status --deep` after recent upgrade/tag experiments.

In my case, the failure rotated across multiple bundled integrations that I do not actively use:

1. `Cannot find module '@larksuiteoapi/node-sdk'`
   - require stack included `dist/extensions/feishu/...`

2. After working around that, `Cannot find module 'nostr-tools'`
   - require stack included `dist/extensions/nostr/...`

3. After that, `Cannot find module '@slack/web-api'`
   - require stack included `dist/extensions/slack/...`

What made this stand out is that manually satisfying one missing package just exposed the next one. That makes it look less like a single bad dependency and more like `status --deep` / bootstrap is eagerly loading bundled optional integrations even when they are not configured or in use.

I stopped there instead of continuing to install more global packages, because that clearly feels like papering over an upstream issue rather than fixing it.

In short:
- this started only recently
- it did not happen before
- `status --deep` appears to trip over optional bundled integrations
- globally installing missing packages only moves the failure to the next integration

**Comment by steipete** [comment]
Fixed on main.

This was the same bundled runtime-dependency staging class, with an extra hardening gap in packaged installs and read-only service/container layouts. Main now:

- repairs/stages bundled runtime deps in doctor/update/runtime paths,
- supports external runtime-dep staging roots for root-owned installs,
- uses a real probe write instead of trusting permission bits, so read-only mount namespaces fall back to external staging,
- skips staged `dist/extensions/*/node_modules` while pruning package `dist`, so npm-created `.bin` symlinks do not abort postinstall before repair.

Relevant commits:

- https://github.com/openclaw/openclaw/commit/f9b20c7d17
- https://github.com/openclaw/openclaw/commit/a99490fba4
- https://github.com/openclaw/openclaw/commit/cc91e8ecf9
- https://github.com/openclaw/openclaw/commit/d4eb236523
- https://github.com/openclaw/openclaw/commit/860cc1b3fe
- https://github.com/openclaw/openclaw/commit/9d66a900e5

For hardened systemd/container deployments, keep `STATE_DIRECTORY` or `OPENCLAW_PLUGIN_STAGE_DIR` pointed at a writable state path. Closing as fixed on main. Note: `openclaw@2026.4.21` is still affected until the next npm release is published.
