### PR TITLE
fix(runtime): add missing tsdown entries for lazy runtime modules

### LINKED ISSUE #65548: Bug: Telegram/Discord incoming message processing crash after commit 74f31241ed
# Bug: Telegram/Discord incoming message processing crash after commit 74f31241ed

## Summary
Commit 74f31241ed (fix(runtime): hide lazy command and context seams from static graph) introduced two blocking bugs that cause message processing to crash on every incoming Telegram/Discord message, and break the `/status` slash command entirely.

## Impact
1. **100% message delivery failure**: No responses are sent to users on Telegram/Discord
2. **Gateway becomes unresponsive**: Repeated crashes eventually cause the gateway to stop processing messages
3. **Broken `/status` command**: The slash command crashes with module not found error

### Bug 1: Missing tsdown build entries
The commit created two new runtime boundary files:
- `src/auto-reply/reply/commands-status-deps.runtime.ts`
- `src/auto-reply/status.runtime.ts`

But these files were **not added** as entries in `tsdown.config.ts`. Without explicit entries, esbuild/tsdown cannot detect the dynamic import pattern `new URL(parts.join(""), baseUrl)` used to load these modules, so these files are **completely omitted from the dist bundle** (they do not appear anywhere in the output dist directory), resulting in `ERR_MODULE_NOT_FOUND` errors at runtime.

### Bug 2: Incorrect relative import path
In `src/auto-reply/reply/commands-status.ts`, the import path was set to:
```ts
const STATUS_RUNTIME_SPEC = ["../status.runtime", ".js"] as const;
```

In production builds, `commands-status.ts` gets code-split to a hashed file directly in the `dist` root directory, so `../status.runtime.js` resolves to the project root directory (outside `dist/`) instead of the expected runtime module path.

## Evidence from logs
```
08:04:52 — Cannot find module dist/commands-status-deps.runtime.js
08:33:58 — Same crash repeated
08:54:30 — Cannot find module /Users/node/dev/openclaw/status.runtime.js (resolved to project root)
08:54:51 — Final crash before gateway became unresponsive
```

## Proposed Fix
1. **Add flat entries to tsdown.config.ts**:
   ```ts
   // Add to the main entry list
   "status.runtime": "src/auto-reply/status.runtime.ts",
   "commands-status-deps.runtime": "src/auto-reply/reply/commands-status-deps.runtime.ts",
   ```

2. **Fix import path in commands-status.ts**:
   ```ts
   // Change from "../status.runtime" to "./status.runtime"
   const STATUS_RUNTIME_SPEC = ["./status.runtime", ".js"] as const;
   ```

## Affected Versions
- All builds including commit 74f31241ed
- Will block the next release unless fixed

## Notes
The dmPolicy was temporarily changed from pairing to open during debugging - this was **not part of the root cause**. The original pairing config was working before this commit.

### PR DESCRIPTION
**Pull request by garnetlyx**
## Summary
This PR fixes a critical regression introduced in commit 74f31241ed that caused crashes during Telegram/Discord incoming message processing and broke the `/status` slash command entirely.

## Root Cause
1. **Missing build entries**: Two new lazy runtime boundary files (`src/auto-reply/status.runtime.ts` and `src/auto-reply/reply/commands-status-deps.runtime.ts`) were added in the commit, but were not registered as entrypoints in `tsdown.config.ts`. This caused them to be omitted from the flattened dist bundle structure, resulting in `ERR_MODULE_NOT_FOUND` errors when imported at runtime.
2. **Path mismatch**: `commands-status.ts` gets code-split to the dist root directory with a hashed filename in production builds. The relative import paths used in source code needed to work both in source-mode execution (Vitest, local TS runners) and bundled production execution.

## Changes
- Added two explicit flat entrypoints to `tsdown.config.ts` to output runtime modules directly to the dist root:
  - `status.runtime`: maps to `src/auto-reply/status.runtime.ts` → outputs to `dist/status.runtime.js`
  - `commands-status-deps.runtime`: maps to `src/auto-reply/reply/commands-status-deps.runtime.ts` → outputs to `dist/commands-status-deps.runtime.js`
- Added a small re-export file at `src/auto-reply/reply/status.runtime.ts` that exports all content from `../status.runtime.ts` to support source-mode execution
- Updated import path in `commands-status.ts` from `../status.runtime` to `./status.runtime` to match both:
  - Source-mode: resolves to the local re-export file
  - Bundle-mode: resolves to the flat runtime module in dist root

## Verification
- ✅ Source-mode execution (tests/development) works correctly
- ✅ Bundled production execution works correctly (runtime modules are in dist root, import paths resolve properly)
- ✅ Telegram/Discord message processing no longer crashes
- ✅ `/status` slash command works as expected

Fixes #65548

### CODE REVIEW

**Comment by mingtsay** [comment]
this PR solved my problem to call `/status` in the chat. thank you a lot!

```
Cannot find module '/auto-reply/reply/commands-status.runtime.js'
```

**Comment by mingtsay** [comment]
oh, I still have issue:

```
 4月 13 19:36:13 h02 node[296352]: 2026-04-13T19:36:13.887+08:00 [tools] session_status failed: Cannot find module '/home/tata/auto-reply/reply/commands-status.runtime.js' imported from /home/tata/openclaw/dist/runtime-import-DxkICcd5.js raw_params={}
```

but I can't solve it by adding the file into `tsdown.config.ts`:

```diff
diff --git a/tsdown.config.ts b/tsdown.config.ts
index 63b84c799f..84c60253ba 100644
--- a/tsdown.config.ts
+++ b/tsdown.config.ts
@@ -150,6 +150,7 @@ function buildCoreDistEntries(): Record<string, string> {
     "commands/status.summary.runtime": "src/commands/status.summary.runtime.ts",
     "infra/boundary-file-read": "src/infra/boundary-file-read.ts",
     "status.runtime": "src/auto-reply/status.runtime.ts",
+    "commands-status.runtime": "src/auto-reply/reply/commands-status.runtime.ts",
     "commands-status-deps.runtime": "src/auto-reply/reply/commands-status-deps.runtime.ts",
     "plugins/provider-discovery.runtime": "src/plugins/provider-discovery.runtime.ts",
     "plugins/provider-runtime.runtime": "src/plugins/provider-runtime.runtime.ts",
```

oh, but the file is in `dist/` so that might not be the root cause...

**Comment by garnetlyx** [comment]
## Root Cause & Fix

The original PR added the missing tsdown entries (`status.runtime`, `commands-status-deps.runtime`), which fixed the immediate `Cannot find module` error for those two modules. However, the deeper issue remained: **`commands-status.ts` and `session-status-tool.ts` both use `importRuntimeModule()` to load `commands-status.runtime.js`**, and that function resolves paths via `new URL(parts.join(""), import.meta.url)` — which is opaque to rollup's static analysis.

### Why it broke

After tsdown/rollup bundling, callers like `session-status-tool.ts` get inlined into hashed chunks at the `dist/` root (e.g. `dist/openclaw-tools-9VCYUim3.js`). Their `import.meta.url` then points to that hashed chunk. The relative path `../../auto-reply/reply/commands-status.runtime` walks **out of `dist/` entirely** → `/home/tata/auto-reply/reply/commands-status.runtime.js` (the exact error @mingtsay reported).

### Why adding a tsdown entry alone didn't fix it

tsdown entries produce stable-named files in `dist/` (e.g. `dist/commands-status.runtime.js`). But `importRuntimeModule` + `new URL()` is invisible to rollup — it can't rewrite these dynamic paths at build time the way it rewrites static `import()` calls.

### The fix (this commit)

Replace all `importRuntimeModule` calls in `commands-status.ts` and `session-status-tool.ts` with **direct `import()` expressions**:

```ts
// Before (broken — opaque to rollup)
importRuntimeModule<CommandsStatusRuntimeModule>(import.meta.url, COMMANDS_STATUS_RUNTIME_SPEC);

// After (working — rollup statically analyzes and rewrites the path)
import("../../auto-reply/reply/commands-status.runtime.js");
```

This matches the existing working pattern used elsewhere (e.g. `get-reply-directives-apply.ts` → `import("./commands-status.runtime.js")`, `model-selection.ts` → `import("../../agents/model-catalog.runtime.js")`). Rollup sees static `import()` and emits `commands-status.runtime.js` as an implicit chunk with the correct resolved path.

Also added `commands-status.runtime` as an **explicit** tsdown entry to guarantee a stable filename (rather than relying on implicit chunk naming).

### Addresses

- @mingtsay's follow-up: `Cannot find module '/home/tata/auto-reply/reply/commands-status.runtime.js'` — this is now fixed by replacing `importRuntimeModule` with direct `import()` in both callers.
- Codex review comment about path alignment — confirmed flat entry keys are correct since callers are inlined into `dist/` root by rollup; the fix avoids `import.meta.url` path resolution entirely.

**Comment by henningsieh** [comment]
I tried it with latest release 2026.4.14: the `/status` slash command works again.

**Comment by steipete** [comment]
Closing this as implemented after Codex review.

Current `main` already fixes the `/status` / `session_status` runtime-import failure through a later, broader refactor that moved shared status rendering into a neutral internal module and switched the tool to a local runtime shim. PR #65561 is superseded by that shipped implementation.

What I checked:

- **Changelog ships the fix in v2026.4.10:** [`CHANGELOG.md`](https://github.com/openclaw/openclaw/blob/c150110e0255/CHANGELOG.md) places `Status/session_status: move shared session status text into a neutral internal status module and keep the tool importing a local runtime shim...` under the `## 2026.4.10` release section, which matches this PR's affected surface. ([`CHANGELOG.md:1031`](https://github.com/openclaw/openclaw/blob/c150110e0255/CHANGELOG.md#L1031), [c150110e0255](https://github.com/openclaw/openclaw/commit/c150110e0255))
- **Exact changelog entry for the runtime-import problem:** The changelog explicitly says built `session_status` no longer depends on reply-command internals or a bundler-opaque runtime import. ([`CHANGELOG.md:1173`](https://github.com/openclaw/openclaw/blob/c150110e0255/CHANGELOG.md#L1173), [c150110e0255](https://github.com/openclaw/openclaw/commit/c150110e0255))
- **Current tool uses a local runtime shim:** `session-status-tool.ts` now lazy-loads [`./session-status.runtime.js`](https://github.com/openclaw/openclaw/blob/c150110e0255/./session-status.runtime.js), so the tool no longer reaches into [`src/auto-reply/reply/commands-status.runtime.js`](https://github.com/openclaw/openclaw/blob/c150110e0255/src/auto-reply/reply/commands-status.runtime.js) or uses `importRuntimeModule()` for this path. ([`src/agents/tools/session-status-tool.ts:68`](https://github.com/openclaw/openclaw/blob/c150110e0255/src/agents/tools/session-status-tool.ts#L68), [c150110e0255](https://github.com/openclaw/openclaw/commit/c150110e0255))
- **Shim re-exports from neutral status module:** `session-status.runtime.ts` is a one-line shim that re-exports `buildStatusText` from the internal status module, which is the architecture the changelog describes. ([`src/agents/tools/session-status.runtime.ts:1`](https://github.com/openclaw/openclaw/blob/c150110e0255/src/agents/tools/session-status.runtime.ts#L1), [c150110e0255](https://github.com/openclaw/openclaw/commit/c150110e0255))
- **Shared status logic now lives outside reply-command internals:** [`src/status/status-text.ts`](https://github.com/openclaw/openclaw/blob/c150110e0255/src/status/status-text.ts) owns `buildStatusText`, and `commands-status.ts` imports that shared module directly instead of being the tool's runtime dependency. ([`src/status/status-text.ts:135`](https://github.com/openclaw/openclaw/blob/c150110e0255/src/status/status-text.ts#L135), [c150110e0255](https://github.com/openclaw/openclaw/commit/c150110e0255))
- **Release tag for the shipped fix exists:** Remote tags include `v2026.4.10`, matching the changelog section where the `session_status` runtime fix was recorded. ([34a56d94d977](https://github.com/openclaw/openclaw/commit/34a56d94d977))

So I’m closing this as already implemented rather than keeping a duplicate issue open.

Review notes: reviewed against [c150110e0255](https://github.com/openclaw/openclaw/commit/c150110e02550eaf6c56db0c851dc62fc0ca88e1); fix evidence: release [v2026.4.10](https://github.com/openclaw/openclaw/releases/tag/v2026.4.10).
