### PR TITLE
Discord: make exec approval timeout configurable

### PR DESCRIPTION
**Pull request by bircheve**
## Summary

- Problem: Discord exec approvals always expired after 2 minutes, even for operators approving from mobile notifications or slower workflows.
- Why it matters: the timeout was hardcoded in the exec approval request path, so Discord config had no way to extend it.
- What changed: added `channels.discord.execApprovals.timeoutMs`, wired channel-owned timeout resolution into approval registration, updated schema/docs, and added focused tests.
- What did NOT change (scope boundary): this PR does not address the separate async follow-up `entry.factory is not a function` failure also mentioned in #49282.

## Change Type (select all)

- [x] Bug fix
- [ ] Feature
- [ ] Refactor
- [x] Docs
- [ ] Security hardening
- [ ] Chore/infra

## Scope (select all touched areas)

- [ ] Gateway / orchestration
- [ ] Skills / tool execution
- [ ] Auth / tokens
- [ ] Memory / storage
- [x] Integrations
- [x] API / contracts
- [ ] UI / DX
- [ ] CI/CD / infra

## Linked Issue/PR

- Related #49282

## User-visible / Behavior Changes

- New optional config: `channels.discord.execApprovals.timeoutMs`
- Discord exec approval requests now honor the configured timeout instead of always using `120000ms`

## Security Impact (required)

- New permissions/capabilities? (`Yes/No`) No
- Secrets/tokens handling changed? (`Yes/No`) No
- New/changed network calls? (`Yes/No`) No
- Command/tool execution surface changed? (`Yes/No`) No
- Data access scope changed? (`Yes/No`) No
- If any `Yes`, explain risk + mitigation:

### Environment

- OS: macOS
- Runtime/container: local dev checkout
- Model/provider: n/a
- Integration/channel (if any): Discord
- Relevant config (redacted): `channels.discord.execApprovals.timeoutMs: 600000`

### Steps

1. Configure Discord exec approvals with a longer `timeoutMs`.
2. Trigger an exec request that requires approval.
3. Observe that the approval stays pending for the configured interval instead of expiring after 2 minutes.

### Expected

- Discord exec approval timeout is configurable per account.

### Actual

- Before this change, the approval request path always used `120000ms`.

## Evidence

Attach at least one:

- [ ] Failing test/log before + passing after
- [x] Trace/log snippets
- [ ] Screenshot/recording
- [ ] Perf numbers (if relevant)

Trace/log summary:
- `pnpm exec oxfmt --check ...` passed on touched files
- `pnpm exec oxlint ...` reported 0 warnings/errors on touched TS files
- `pnpm tsgo` still reports unrelated pre-existing repo failures outside this diff
- local `vitest` / `codex review` did not complete cleanly in this environment, so this PR does not claim a passing runtime test run here

## Human Verification (required)

What you personally verified (not just CI), and how:

- Verified scenarios: traced the request path from Discord config -> channel adapter -> exec approval registration payload and confirmed the configured timeout is threaded through to `exec.approval.request`
- Edge cases checked: missing/invalid timeout falls back to the default; non-Discord surfaces continue using the default timeout
- What you did **not** verify: a successful end-to-end Vitest or live Discord run in this local environment

## Review Conversations

- [ ] I replied to or resolved every bot review conversation I addressed in this PR.
- [ ] I left unresolved only the conversations that still need reviewer or maintainer judgment.

## Compatibility / Migration

- Backward compatible? (`Yes/No`) Yes
- Config/env changes? (`Yes/No`) No
- Migration needed? (`Yes/No`) No
- If yes, exact upgrade steps:

## Failure Recovery (if this breaks)

- How to disable/revert this change quickly: remove `channels.discord.execApprovals.timeoutMs` or revert this commit
- Files/config to restore: Discord exec approval config and the touched exec approval request plumbing
- Known bad symptoms reviewers should watch for: approval requests ignoring the configured timeout or expiring immediately

## Risks and Mitigations

- Risk: a non-Discord channel could accidentally inherit Discord-specific timeout behavior
- Mitigation: timeout resolution goes through the generic channel adapter and falls back to the default

AI-assisted: yes (Codex)

### CODE REVIEW

File: src/infra/exec-approval-surface.ts [hunk 1]
```diff
@@ -22,6 +23,13 @@ function labelForChannel(channel?: string): string {
   }
 }
 
+function normalizeTimeoutMs(value: unknown, fallback: number): number {
+  if (typeof value !== "number" || !Number.isFinite(value)) {
+    return fallback;
+  }
+  return Math.max(1, Math.floor(value));
+}
```
[the remark this answers is not in the document]
Comment (bircheve) [reply src/infra/exec-approval-surface.ts]: Fixed in a05fb2e501: moved timeout normalization into shared exec-approval infra and reused it from the surface resolver, request path, and Discord plugin runtime export.

File: src/agents/bash-tools.exec-approval-request.ts [hunk 2]
```diff
@@ -51,7 +56,7 @@ function buildExecApprovalRequestToolParams(
     turnSourceTo: params.turnSourceTo,
     turnSourceAccountId: params.turnSourceAccountId,
     turnSourceThreadId: params.turnSourceThreadId,
-    timeoutMs: DEFAULT_APPROVAL_TIMEOUT_MS,
+    timeoutMs,
```
[the remark this answers is not in the document]
Comment (bircheve) [reply src/agents/bash-tools.exec-approval-request.ts:66]: Fixed in a05fb2e501: `waitDecision` now uses the effective approval timeout plus the existing transport buffer, and the async follow-up path threads that timeout through instead of falling back to 130s. Added a focused assertion in `bash-tools.exec-approval-request.test.ts`.

File: src/config/zod-schema.providers-core.ts [hunk 3]
```diff
@@ -522,6 +522,7 @@ export const DiscordAccountSchema = z
       .object({
         enabled: z.boolean().optional(),
         approvers: DiscordIdListSchema.optional(),
```
[the remark this answers is not in the document]
Comment (bircheve) [reply src/config/zod-schema.providers-core.ts:524]: Fixed in a05fb2e501: added a 24h schema cap for `channels.discord.execApprovals.timeoutMs` and a config validation test for values above that limit.

**Comment by steipete** [comment]
Closing this as not reproducible on current `main` after Codex review.

Current `main` no longer matches the PR’s reported bug: exec approvals now default to 30 minutes end-to-end, so the old hardcoded 2-minute expiry is obsolete. The proposed Discord-specific `channels.discord.execApprovals.timeoutMs` setting is not present on `main`, but the specific behavior this PR was fixing does not reproduce against current code.

What I checked:

- **Current exec approval default is 30 minutes:** `DEFAULT_EXEC_APPROVAL_TIMEOUT_MS` is `1_800_000`, not `120_000`. ([`src/infra/exec-approvals.ts:167`](https://github.com/openclaw/openclaw/blob/9ece33c50506/src/infra/exec-approvals.ts#L167), [9ece33c50506](https://github.com/openclaw/openclaw/commit/9ece33c50506))
- **Agent request path forwards the shared default timeout:** `buildExecApprovalRequestToolParams()` sends `timeoutMs: DEFAULT_APPROVAL_TIMEOUT_MS`, so the request path is no longer hardcoded to 2 minutes. ([`src/agents/bash-tools.exec-approval-request.ts:55`](https://github.com/openclaw/openclaw/blob/9ece33c50506/src/agents/bash-tools.exec-approval-request.ts#L55), [9ece33c50506](https://github.com/openclaw/openclaw/commit/9ece33c50506))
- **Transport wait timeout scales from the approval timeout:** `DEFAULT_APPROVAL_REQUEST_TIMEOUT_MS` is derived as `DEFAULT_APPROVAL_TIMEOUT_MS + 10_000`, so the wait path also tracks the 30-minute approval window. ([`src/agents/bash-tools.exec-runtime.ts:122`](https://github.com/openclaw/openclaw/blob/9ece33c50506/src/agents/bash-tools.exec-runtime.ts#L122), [9ece33c50506](https://github.com/openclaw/openclaw/commit/9ece33c50506))
- **Gateway still honors explicit timeout values:** The server method accepts `timeoutMs` and falls back to `DEFAULT_EXEC_APPROVAL_TIMEOUT_MS`, so current main supports long-lived approvals without the old 120-second default. ([`src/gateway/server-methods/exec-approval.ts:145`](https://github.com/openclaw/openclaw/blob/9ece33c50506/src/gateway/server-methods/exec-approval.ts#L145), [9ece33c50506](https://github.com/openclaw/openclaw/commit/9ece33c50506))
- **Discord docs describe the current 30-minute behavior:** The Discord docs say approvals expire after 30 minutes by default, which contradicts the PR’s reported current behavior of always expiring after 2 minutes. Public docs: [`docs/channels/discord.md`](https://docs.openclaw.ai/channels/discord). ([`docs/channels/discord.md:900`](https://docs.openclaw.ai/channels/discord), [9ece33c50506](https://github.com/openclaw/openclaw/commit/9ece33c50506))
- **The PR’s exact config knob is not on main:** `DiscordExecApprovalConfig` and the Discord Zod schema include `enabled`, `approvers`, filters, cleanup, and `target`, but no `timeoutMs` field, so this is not an implemented-on-main match. ([`src/config/types.discord.ts:141`](https://github.com/openclaw/openclaw/blob/9ece33c50506/src/config/types.discord.ts#L141), [9ece33c50506](https://github.com/openclaw/openclaw/commit/9ece33c50506))

Review notes: reviewed against [9ece33c50506](https://github.com/openclaw/openclaw/commit/9ece33c50506ba031df382f69bde65dfda19bea5).
