### ISSUE TITLE
openclaw-lark plugin fails to load after OpenClaw 2026.4.27: Cannot find module openclaw/plugin-sdk/zalouser

### ISSUE THREAD

**Issue by Goron01** [clawdbot/clawdbot#74702]
## Bug Description

After updating OpenClaw to 2026.4.27, the `@larksuite/openclaw-lark` plugin (tried versions 2026.4.7 and 2026.4.8) fails to load with the following error:

```
Error: Cannot find module /openclaw/dist/plugin-sdk/root-alias.cjs/zalouser
  - /home/goron/.openclaw/extensions/openclaw-lark/src/messaging/inbound/handler.js
```

The plugin handler.js contains:
```javascript
const zalouser_1 = require("openclaw/plugin-sdk/zalouser");
```

This subpath `openclaw/plugin-sdk/zalouser` appears to no longer be exported by the OpenClaw plugin SDK in 2026.4.27.

## Environment

- **OpenClaw version:** 2026.4.27
- **Plugin version:** 2026.4.7 and 2026.4.8 (both fail)
- **Plugin SDK location:** `~/.npm-global/lib/node_modules/openclaw/dist/plugin-sdk/`
- **zalouser plugin:** 2026.3.22 is installed as a separate plugin

## What was tried

1. Installed `@openclaw/zalouser` plugin separately - did not fix the issue
2. Updated lark plugin from 2026.4.7 to 2026.4.8 - same error
3. The `zalouser` subpath does not exist in `dist/plugin-sdk/root-alias.cjs` in 2026.4.27

## Analysis

The `root-alias.cjs` in OpenClaw 2026.4.27 does not export a `zalouser` subpath, but the lark plugin (and likely zalouser itself) depends on `require("openclaw/plugin-sdk/zalouser")`. This appears to be a breaking change in the plugin SDK between OpenClaw versions.

## Expected behavior

The lark plugin should load successfully or provide a clear migration path.

**Comment by steipete** [comment]
Fixed on main.

What landed:
- Restored the deprecated `openclaw/plugin-sdk/zalouser` facade as a narrow compatibility wrapper around `plugin-sdk/command-auth`.
- Updated package exports, SDK entrypoints, docs, API baseline, and contract/root-alias coverage.

Commits:
- https://github.com/openclaw/openclaw/commit/db18323551
- https://github.com/openclaw/openclaw/commit/a89fe0f5a0

Proof before push: package-contract/root-alias tests, command-auth tests, `pnpm plugin-sdk:check-exports`, `pnpm plugin-sdk:api:check`, Testbox `pnpm build`, and Testbox `pnpm check:changed`.
