### ISSUE TITLE
[Bug] v2026.4.11 breaks minimax/vydra plugins: openai v6.34.0 ESM export mismatch

### ISSUE THREAD

**Issue by vliuyt** [clawdbot/clawdbot#65089]
**Description**: After updating to v2026.4.11, the minimax and vydra bundled plugins fail to load.

**Error**:
```
[plugins] minimax failed to load from .../openclaw/dist/extensions/minimax/index.js: Error: Cannot find module \"./completions/completions.js\"
Require stack:
- .../@mariozechner/pi-ai/node_modules/openai/resources/chat/chat.js
[plugins] vydra failed to load from .../openclaw/dist/extensions/vydra/index.js: Error: Cannot find module \"./completions/completions.js\"
```

**Root Cause**: The openai npm package v6.34.0 has an ESM export misconfiguration — `package.json` exports point to `./index.mjs` but that file does not exist. This causes the pi-ai module resolution to fail.

**Impact**: All users upgrading to v2026.4.11 are blocked — the gateway refuses to start because the config is considered invalid when bundled plugins fail to load.

**Fix Applied** (workaround): Manually changed the export in the openai package at:
`node_modules/@mariozechner/pi-ai/node_modules/openai/package.json`
Changed: `".": { "import": "./index.mjs" }` → `".": { "import": "./index.js" }`

Then reinstalled pi-ai dependencies: `cd node_modules/@mariozechner/pi-ai && npm install`

**Environment**: macOS arm64, Node v24.13.0, OpenClaw 2026.4.11

**Comment by obviyus** [comment]
Checked again on current `main` at `3f65e2545f` on April 12, 2026 and could not reproduce this.

Current `@mariozechner/pi-ai@0.66.1` resolves its nested `openai` dependency to `6.26.0`, and the reported `openai/resources/chat/chat.js` load path succeeds in the current tree.

Closing as not reproducible on current `main`.
