### ISSUE TITLE
[Bug]: Microsoft Teams Asymmetrical communication

### ISSUE THREAD

**Issue by mikelavrik** [clawdbot/clawdbot#73167]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

Microsoft Teams inbound messages stopped reaching OpenClaw after upgrading from 2026.4.9 to 2026.4.25/2026.4.26.

Outbound Teams sending still works, and Discord still works both directions. Downgrading to 2026.4.9 restores Teams replies.

## Reproduction steps
1. Run OpenClaw 2026.4.9 with Microsoft Teams configured.
2. Send a Teams DM or @mention the bot in a Teams group chat.
3. Confirm the agent replies.
4. Upgrade to OpenClaw 2026.4.26.
5. Send the same Teams DM or group @mention.
6. Observe no reply and no new OpenClaw log movement.
7. Downgrade to 2026.4.9.
8. Observe Teams replies working again.

### Expected behavior

Teams DMs and @mentioned group messages should be received by OpenClaw and routed to the agent.

### Actual behavior

Teams messages appear to never reach OpenClaw inbound handling/logging on 2026.4.25/2026.4.26.

### OpenClaw version

- Broken: OpenClaw 2026.4.25 and 2026.4.26

### Operating system

ubuntu 24

### Install method

npm

### Model

minimax

### Provider / routing chain

minimax

### Logs, screenshots, and evidence

```shell

```

## Additional notes
This looks like a Teams inbound webhook/listener regression because there is no OpenClaw log movement when messages are sent, while outbound Teams sending still works.

**Comment by cdstg** [comment]
Can confirm the same issue 2026.4.15 is Ok 2026.4.26  even after setting
],
      "authType": "secret",
      "appPassword": "abc"
    }

In the config

**Comment by BradGroux** [comment]
I hit what looks like the same regression on a macOS/npm install after updating to `2026.4.26`.

Symptoms matched the issue report:

- Teams inbound DMs/@mentions stopped routing to the agent
- outbound/proactive Teams sends still worked
- Azure Bot Service config was unchanged and still valid
- listener/gateway were up locally

The useful local signature was in the Teams inbound auth path:

```text
MSTEAMS_JWT_VALIDATION_ERROR
jwt.verify is not a function
```

Local package/runtime context:

- `@microsoft/agents-hosting` `1.3.1`
- `jsonwebtoken` `9.0.3`
- OpenClaw `2026.4.26`

A local runtime hotfix that restored inbound Teams was normalizing the dynamic `jsonwebtoken` import before calling `verify`:

```ts
jwt: jwtModule.default ?? jwtModule
```

So this looks like a Teams inbound JWT validation regression from the update/runtime packaging path, not an Azure bot configuration issue. There was also local allowlist cleanup during troubleshooting, but that was separate from the upstream failure above.

I'll open a PR referencing this issue with the import normalization fix.

**Comment by astotle-vt** [comment]
Same issue here after upgrading to 2026.4.26. MacOS as well.

**Comment by BradGroux** [comment]
> Same issue here after upgrading to 2026.4.26. MacOS as well.

PR should be up momentarily.

EDIT: The code fix is already on `main` in `b3bc60ae25` (`fix(msteams): unwrap jwt runtime deps`). This PR #74130 avoids duplicating that patch and only connects the release note to the additional confirmed regression report.

**Comment by juanflexoffers** [comment]
We can reproduce this on Windows with OpenClaw 2026.4.26: the bundled `msteams` channel intermittently fails to load due to an EPERM rename in `plugin-runtime-deps`, which then causes very long “starting channels and sidecars…” delays (4–6 minutes) and Teams stops responding.

Environment
- OS: Windows (10.0.17763)
- Node: 22.22.0
- OpenClaw: 2026.4.26 (installed via `npm i -g openclaw@2026.4.26`)
- Channel: msteams (Bot Framework), webhook path `/api/messages`

Gateway log (repeatable)
- `[channels] failed to load bundled channel msteams: EPERM: operation not permitted, rename 'C:\\Users\\Milo.Claw\\.openclaw\\plugin-runtime-deps\\openclaw-2026.4.26-9d7065a6dc84\\dist\\extensions\\.plugin-msteams-XXXXX\\plugin' -> 'C:\\Users\\Milo.Claw\\.openclaw\\plugin-runtime-deps\\openclaw-2026.4.26-9d7065a6dc84\\dist\\extensions\\msteams'`

Impact
- Gateway startup repeatedly stalls at “starting channels and sidecars…”, then eventually starts much later.
- Azure Bot “Microsoft Teams” channel shows Issues / Internal server error and timeouts; bot does not reply.

Notes / workaround
- Suspect AV/Defender file lock on `%USERPROFILE%\\.openclaw\\plugin-runtime-deps\\...`.
- Downgrading to 2026.4.14 restores normal startup time and Teams replies (same config). Excluding that directory + deleting the `openclaw-2026.4.26-*` runtime-deps folder may help, but the underlying EPERM rename on Windows remains.
