### ISSUE TITLE
Gateway restart strips askFallback from exec-approvals.json, silently breaking cron exec

### ISSUE THREAD

**Issue by groksrc** [clawdbot/clawdbot#67747]
## Description

The gateway process rewrites `~/.openclaw/exec-approvals.json` on restart but its serializer drops the `askFallback` key. This silently degrades the effective exec policy for cron jobs, causing them to be denied with no way to recover without manual intervention.

This is a recurring issue — every `openclaw gateway restart` (including restarts triggered by config changes or updates) strips the key, so the fix doesn't stick.

## Root Cause

Two things combine to cause this:

1. **The gateway serializer doesn't preserve `askFallback`** — it only writes back `ask`, `security`, and `socket`/`version` fields. Any other keys (including `askFallback`) are dropped on the next write.

2. **The exec tool hardcodes `security: "allowlist"` and `ask: "on-miss"` in cron exec calls** (visible in the raw tool params). OpenClaw merges exec-approvals.json with these tool-level defaults and takes the **stricter** value. So even with `ask: "off"` in the config, the tool's `ask: "on-miss"` wins. The `askFallback: "allow"` was the only thing making cron work — when the interactive prompt can't happen (no human in the loop), it falls to `askFallback`.

## Reproduction Steps

1. Configure `~/.openclaw/exec-approvals.json`:

```json
{
  "version": 1,
  "defaults": {
    "ask": "off",
    "askFallback": "allow"
  },
  "agents": {
    "main": {
      "ask": "off",
      "askFallback": "allow"
    }
  }
}
```

2. Verify a cron job with an exec tool call works (e.g., any skill that runs a shell command).

3. Run `openclaw gateway restart`.

4. Read `~/.openclaw/exec-approvals.json` — `askFallback` is gone:

```json
{
  "version": 1,
  "defaults": {
    "ask": "off"
  },
  "agents": {
    "main": {
      "ask": "off"
    }
  }
}
```

5. Wait for the next cron exec — it is denied.

## Error Log

From `~/.openclaw/logs/gateway.err.log`:

```
[tools] exec failed: exec denied: Cron runs cannot wait for interactive exec approval.
Effective host exec policy: security=allowlist ask=on-miss askFallback=allowlist
Stricter values from tools.exec and ~/.openclaw/exec-approvals.json both apply.
```

Note the raw tool params confirm the hardcoded defaults:
```json
{"command":"...","security":"allowlist","ask":"on-miss"}
```

## Expected Behavior

- The gateway should preserve all keys in `exec-approvals.json` when rewriting the file (or not rewrite it at all if only reading).
- `ask: "off"` in exec-approvals.json should take precedence over the exec tool's hardcoded `ask: "on-miss"` — the file-level policy is an explicit operator override.
- Cron sessions with `ask: "off"` should not require `askFallback` as a workaround.

## Workaround

A macOS LaunchAgent using `WatchPaths` monitors `exec-approvals.json` and restores `askFallback: "allow"` whenever it is stripped. This auto-heals after each gateway restart but shouldn't be necessary.

## Environment

- OpenClaw: 2026.4.11
- macOS (arm64)
- Node: 25.8.1
- Gateway: bare metal LaunchAgent (no Docker)
- Single-user deployment, single agent (`main`)

## Related Issues

- #16348 (closed/stale) — per-agent exec-approvals config ignored for cron sessions
- #49266 (closed) — cannot fully disable exec approval system; notes exec-approvals.json recreated on restart
- #63211 (open) — isolated cron sessions ignore `ask: "off"` policy

**Comment by martingarramon** [comment]
Confirming this reproduces, but the diagnosis needs a small correction — the serializer does preserve `askFallback`. The schema at `src/gateway/protocol/schema/exec-approvals.ts` and the file type at `src/infra/exec-approvals.ts` both include it.

The field is being **stripped by value-validation**, not by the key round-trip. In `sanitizeExecApprovalPolicy` (`src/infra/exec-approvals.ts:347-363`), `askFallback` is coerced to `undefined` unless the value is exactly `"deny" | "allowlist" | "full"`. Your config has `"askFallback": "allow"`, which is not a member of that enum, so it gets silently dropped every time the gateway boots and `ensureExecApprovals` writes back the normalized file (`exec-approvals.ts:520-534` calls `saveExecApprovals(updated)` on every startup).

This sanitizer was introduced in #59112 (commit `a597938be8`, "strip invalid approval policy enums during config normalization") — but with no logging when it strips a known key with an unknown value, so the behavior looks like key loss.

Two concrete suggestions:

1. Changing `"allow"` → `"allowlist"` in your `exec-approvals.json` should stop the LaunchAgent auto-heal loop immediately.
2. Worth having the sanitizer `log.warn` when it strips a known-key-with-unknown-value, so this class of silent config degradation is discoverable.

Separately, the policy-merge behavior you described (tool-level `ask: "on-miss"` winning over file-level `ask: "off"`) is orthogonal to the stripping — worth filing as its own issue so the two traces can move independently.

**Comment by steipete** [comment]
Closing this as not reproducible on current `main` after Codex review.

Issue #67747 does not describe a current-main gateway serializer bug. Current code, tests, and docs all treat `askFallback` as an enum limited to `deny | allowlist | full`, so the reported `askFallback: "allow"` is normalized away on load and then written back during gateway startup. The other requested behavior change in the issue body also conflicts with the documented/current contract: requested `tools.exec.*` policy and host approvals are merged conservatively, with stricter security and more aggressive ask winning.

What I checked:

- **`askFallback` is a security enum, not a free-form string:** Current exec approval types define `askFallback` as `ExecSecurity`, and the normalizer only preserves `deny`, `allowlist`, or `full`; any other string becomes `undefined`. That matches the behavior the commenter described and means `"allow"` is unsupported, not silently omitted by a serializer bug. ([`src/infra/exec-approvals.ts:122`](https://github.com/openclaw/openclaw/blob/fa976e5b93b3/src/infra/exec-approvals.ts#L122), [fa976e5b93b3](https://github.com/openclaw/openclaw/commit/fa976e5b93b3))
- **Gateway startup rewrites the normalized file every time:** `ensureExecApprovals()` loads the file, normalizes it, fills socket defaults, and always calls `saveExecApprovals(updated)`. So restart can rewrite the file, but with normalized schema values rather than by dropping the `askFallback` key itself. ([`src/infra/exec-approvals.ts:520`](https://github.com/openclaw/openclaw/blob/fa976e5b93b3/src/infra/exec-approvals.ts#L520), [fa976e5b93b3](https://github.com/openclaw/openclaw/commit/fa976e5b93b3))
- **Tests explicitly lock in invalid-value stripping:** Current tests assert that invalid `defaults.askFallback` values are dropped and valid values are preserved, and they likewise drop invalid agent-level `askFallback` values. That makes the current-main behavior intentional and covered. ([`src/infra/exec-approvals-config.test.ts:379`](https://github.com/openclaw/openclaw/blob/fa976e5b93b3/src/infra/exec-approvals-config.test.ts#L379), [fa976e5b93b3](https://github.com/openclaw/openclaw/commit/fa976e5b93b3))
- **Docs define supported `askFallback` values and conservative merge semantics:** The public exec approvals docs say effective policy is the stricter combination of `tools.exec.*` and host approvals, and list `askFallback` values as only `deny`, `allowlist`, or `full`. That contradicts the issue's expectation that host `ask: off` should override requested `ask: on-miss`, and also contradicts `askFallback: "allow"`. Public docs: [`docs/tools/exec-approvals.md`](https://docs.openclaw.ai/tools/exec-approvals). ([`docs/tools/exec-approvals.md:17`](https://docs.openclaw.ai/tools/exec-approvals), [fa976e5b93b3](https://github.com/openclaw/openclaw/commit/fa976e5b93b3))
- **Policy summary code and tests confirm stricter host/more-aggressive ask precedence:** Current policy resolution computes effective security with `minSecurity(...)`, effective ask with `maxAsk(...)`, and tests assert that host `allowlist` / `always` beats requested `full` / `off`. The issue's requested precedence reversal is not current behavior. ([`src/infra/exec-approvals-effective.ts:238`](https://github.com/openclaw/openclaw/blob/fa976e5b93b3/src/infra/exec-approvals-effective.ts#L238), [fa976e5b93b3](https://github.com/openclaw/openclaw/commit/fa976e5b93b3))

Review notes: reviewed against [fa976e5b93b3](https://github.com/openclaw/openclaw/commit/fa976e5b93b3819f9e137fe08635764edee38290).
