### ISSUE TITLE
[Bug]: Missing dependencies for extensions (Feishu, Nostr) in global install 2026.4.21

### ISSUE THREAD

**Issue by alexandre-leng** [clawdbot/clawdbot#70198]
<img width="982" height="389" alt="Image" src="https://github.com/user-attachments/assets/d55e978f-ea80-42fd-bd09-baada29cc013" />

### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

When installing and running openclaw globally via npm, the application crashes due to missing dependencies required by some built-in extensions (Feishu, Nostr).

These dependencies are not installed automatically, causing runtime errors.

### Steps to reproduce

Install openclaw globally:
npm install -g openclaw
Run openclaw
Observe errors like:
Error: Cannot find module '@larksuiteoapi/node-sdk'
Require stack:
...openclaw/dist/extensions/feishu/...

and:

Error: Cannot find module 'nostr-tools'
Require stack:
...openclaw/dist/extensions/nostr/...

### Expected behavior

All required dependencies for bundled extensions should be installed automatically, or optional extensions should not be loaded unless explicitly enabled.

### Actual behavior

The app crashes at runtime due to missing modules required by extensions that are enabled by default.

### OpenClaw version

2026.4.21

### Operating system

windows 11 

### Install method

iwr -useb https://openclaw.ai/install.ps1 | iex

### Model

minimax 2.5 opencode

### Provider / routing chain

opencode

### Additional provider/model setup details

OS: Windows (PowerShell)
Node.js version: v24.14.0
npm version: 11.9.0
Installation method: global (npm install -g openclaw)

### Logs, screenshots, and evidence

```shell

```

**Comment by BestHuang** [comment]
I also encountered this error when installing on Linux. Please fix it as soon as possible.
I suggest not bundling Feishu.

**Comment by alexandre-leng** [comment]
## Code-level analysis of the issue

The runtime errors strongly suggest that certain extension modules are importing external dependencies without verifying their availability, which leads to immediate crashes when those dependencies are not installed.

For example, based on the stack traces, files such as:

```
dist/extensions/feishu/client-*.js
dist/extensions/nostr/setup-*.js
```

appear to directly import their respective SDKs at the top level of the module.

The issue likely comes from patterns similar to:

```js
const lark = require("@larksuiteoapi/node-sdk")
```

and:

```js
const nostr = require("nostr-tools")
```

Because these `require` calls are executed at module load time, Node.js attempts to resolve them immediately when the extension file is imported. If the dependency is not installed, the process throws a `MODULE_NOT_FOUND` error and terminates.

This behavior becomes problematic if the application loads all extensions eagerly during startup. In that case, even unused or unconfigured extensions will still attempt to resolve their dependencies.

A safer implementation would defer loading or guard these imports. For instance, the dependency could be required inside a function and wrapped in a try/catch block:

```js
function loadNostr() {
  try {
    return require("nostr-tools")
  } catch (err) {
    return null
  }
}
```

or:

```js
let nostr
try {
  nostr = require("nostr-tools")
} catch (err) {
  // dependency not available, extension should disable itself
}
```

Additionally, extension initialization should check whether the dependency is available before continuing:

```js
if (!nostr) {
  // skip initialization or log a warning instead of crashing
  return
}
```

Another possible contributing factor is that these dependencies may not be declared correctly in the main `package.json`, or are listed as optional without proper handling. If they are intended to be optional, the runtime must explicitly account for their absence.

Finally, the extension loading mechanism itself is likely eager. If there is a central loader that imports all extensions unconditionally (for example, iterating over a directory and requiring each file), then any missing dependency in any extension will break the entire application.

A more robust design would involve lazy-loading extensions only when they are enabled in configuration, or dynamically importing them at the moment they are actually used.

Overall, the combination of top-level `require` calls and eager extension loading creates a fragile system where optional features become mandatory at runtime.

[install.txt](https://github.com/user-attachments/files/26973185/install.txt)

**Comment by PratikRai0101** [comment]
Hey,
I would like to work on this issue and I will open a draft pr shortly

**Comment by Sutherlandon** [comment]
Got this installing on MacOS as well when trying to set up openclaw for the first time

**Comment by HomemadeToast57** [comment]
i experienced this and also realized its impacting models.list

**Comment by jeffwweee** [comment]
Hey seems like not just those stated. I met with 4 so far when running openclaw onboard. Here's my list:

OP's 2, 
@slack/web-api
@whiskeysockets/baileys

what i did as a manual workaround is manually go around and do npm install for the missing module

**Comment by rafiki270** [comment]
## Triage Verdict: INVALID — Duplicate of #70099

**Swarm: 3/3 reviewers | All DUPLICATE (avg conf: 0.94)**

This issue reports the same regression bug as #70099 with no new angle:

- **Same root cause:**  glob pattern excludes  from the npm bundle
- **Same missing modules:**  (Feishu) +  (Nostr) — identical to #70099
- **Same install method:** global npm install on both Windows (#70198) and Linux/Debian (#70099)
- **Platform-agnostic:** bug manifests identically across OS; Windows is not a distinguishing factor
- **No new extension coverage:** #70099 also covers Slack (); #70198 is a strict subset

**Action:** This is a duplicate. The fix for #70099 will resolve both issues.

---
*Triage by OpenClaw agent — 2026-04-22 16:09 UTC*

**Comment by steipete** [comment]
Fixed on main.

The 2026.4.20/2026.4.21 packages could leave bundled plugin runtime deps missing, so enabled/loaded bundled plugins such as Feishu, Telegram, Slack, Nostr, and WhatsApp could fail with `Cannot find module ...` during install, update, doctor, status, or gateway startup.

Main now repairs/stages bundled plugin runtime deps before plugin/channel runtime load and during doctor/update recovery, with release-check and Docker coverage for the packed install path. Relevant commits:

- https://github.com/openclaw/openclaw/commit/f9b20c7d17
- https://github.com/openclaw/openclaw/commit/a99490fba4
- https://github.com/openclaw/openclaw/commit/cc91e8ecf9
- https://github.com/openclaw/openclaw/commit/d4eb236523
- https://github.com/openclaw/openclaw/commit/860cc1b3fe

Closing as fixed on main. Note: `openclaw@2026.4.21` is still affected until the next npm release is published.

**Comment by coolmanns** [comment]
We hit what looks like the same packaged/global-install failure on Linux after updating a global npm install from 2026.4.20 to 2026.4.21.

Environment
- Host: Linux
- Install style: global npm install under ~/.npm-global/lib/node_modules/openclaw
- Gateway managed separately; updater signaled restart, but the running gateway version lagged until explicit restart/verification

Observed sequence
1. Update to 2026.4.21 succeeded at the npm layer.
2. `openclaw status` then failed on bundled Feishu missing `@larksuiteoapi/node-sdk`.
3. After manually repairing Feishu in `dist/extensions/feishu/node_modules`, `openclaw status` then failed on bundled `nostr` missing `nostr-tools`.
4. A broader staged-runtime-deps repair across bundled extensions was needed before `openclaw status` worked again.
5. `openclaw doctor --fix` helped with `microsoft` / `node-edge-tts`, but did not repair Feishu in our case.

That made this look broader than a Feishu-only miss: Feishu was just the first failing bundled extension we hit, then Nostr surfaced immediately after.

The local extension set we had to repair included:
- Feishu (manual first)
- Nostr
- plus a broader staged-deps sweep over bundled extensions including codex, diffs, google, matrix, qqbot, slack, webhooks, and whatsapp

So from our side, `#70138` + this issue together describe the incident best, and `#70123` also fits because `doctor --fix` did not fully recover the broken bundled deps path.
