### ISSUE TITLE
[Bug]: 2026.4.25 stable breaks Intel macOS LaunchAgent + BlueBubbles after upgrade from 4.23; rollback restores service

### ISSUE THREAD

**Issue by SoumyaBanerjee2025** [clawdbot/clawdbot#72909]
### Bug type

Regression (worked before, now fails)

### Summary

Upgrading a stable OpenClaw 2026.4.23 install to 2026.4.25 stable caused a macOS LaunchAgent-managed gateway to appear partially alive, but BlueBubbles/iMessage delivery became unreliable/unusable. CLI/channel probes were slow or timing out, the agent stopped responding consistently over iMessage, and logs showed a 2026.4.25 plugin-runtime-deps module failure during BlueBubbles catchup.

Rolling back to 2026.4.23 and restoring the pre-upgrade config restored normal service.

This looks related to #72848 and possibly #72846, but this report includes a BlueBubbles/runtime-deps failure on macOS Intel.

### Environment

- OpenClaw before upgrade: 2026.4.23
- OpenClaw attempted upgrade: 2026.4.25 stable
- Rollback target: 2026.4.23
- OS: macOS on Intel MacBook Air 2019
- Gateway service: macOS LaunchAgent
- Channel: BlueBubbles / iMessage
- Machine role: headless always-on Mac

### Steps to reproduce

1. Start from a working 2026.4.23 install on macOS Intel with BlueBubbles configured.
2. Upgrade to 2026.4.25 stable.
3. Restart gateway / LaunchAgent.
4. Send iMessage to the BlueBubbles-backed agent.
5. Observe gateway/channel instability or no response.
6. Roll back to 2026.4.23 and restore the previous config.
7. BlueBubbles works again.

### Expected behavior

After upgrading to 2026.4.25, the LaunchAgent gateway should restart cleanly and BlueBubbles catchup/reply handling should continue working.

### Actual behavior

After upgrade, gateway/channel behavior became unreliable. BlueBubbles did not consistently process/respond. Logs included a plugin runtime dependency failure:

```text
[bluebubbles] [default] BlueBubbles catchup: unexpected failure:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module
'/Users/<user>/.openclaw/plugin-runtime-deps/openclaw-2026.4.25-17c3fa238f70/dist/paths-BFfL0I8G.js'
imported from
'/Users/<user>/.openclaw/plugin-runtime-deps/openclaw-2026.4.25-17c3fa238f70/dist/catchup-3W0avzeW.js'
```

During rollback testing, logs also showed newer-version config contamination when trying 2026.4.24 after 2026.4.25:

```text
Config was last written by a newer OpenClaw (2026.4.25); current version is 2026.4.24.
```

After rolling back to 2026.4.23 and restoring the pre-upgrade config, channel probe succeeds:

```text
OpenClaw 2026.4.23 (a979721)
Gateway reachable.
BlueBubbles default: enabled, configured, running, connected, works
```

### Impact

High for BlueBubbles/iMessage users on macOS Intel. The gateway can appear present, but the agent becomes unavailable or unreliable until rollback.

### Related issues

- #72848: OpenClaw no longer works after update from 4.23 to 4.24/4.25 on Intel Mac
- #72846: v2026.4.25 channel sidecar startup regression after ready

**Comment by SoumyaBanerjee2025** [comment]
Adding one clarification because this may help triage: the failure shape here looks very close to #72848 — Intel Mac, working 2026.4.23 install, upgrade to 2026.4.25 stable, gateway process appears present but the agent/channel becomes unusable, rollback to 2026.4.23 restores service.

The extra evidence in this case is the BlueBubbles catchup/runtime-deps error:

```text
[bluebubbles] [default] BlueBubbles catchup: unexpected failure:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module
'/Users/<user>/.openclaw/plugin-runtime-deps/openclaw-2026.4.25-17c3fa238f70/dist/paths-BFfL0I8G.js'
imported from
'/Users/<user>/.openclaw/plugin-runtime-deps/openclaw-2026.4.25-17c3fa238f70/dist/catchup-3W0avzeW.js'
```

So this may be the same broader 4.25 Intel/macOS upgrade regression as #72848, with a specific BlueBubbles/runtime dependency symptom rather than only a generic gateway timeout.

**Comment by steipete** [comment]
Verified this specific BlueBubbles/runtime-deps failure is fixed on current `main`.

What I checked:
- Current built BlueBubbles catchup chunk imports `./paths-*.js`, and the referenced `paths-*.js` file exists in `dist`; a direct import-graph scan of `dist/catchup-*.js` found no missing relative imports.
- The runtime mirror path now materializes root `dist` JS chunks instead of leaving them as stale symlinks when they are plugin-owned or have only relative/builtin imports. That covers the exact reported shape: `catchup-*.js` copied into `~/.openclaw/plugin-runtime-deps/.../dist/` but its relative `paths-*.js` dependency missing.
- Regression coverage is in `src/plugins/bundled-runtime-root.test.ts` and `src/plugins/loader.test.ts` for materializing root JS chunks in external runtime mirrors and reloading from that mirror.

Verification run:
- `pnpm test src/plugins/bundled-runtime-root.test.ts src/plugins/bundled-runtime-deps.test.ts src/plugins/loader.test.ts` -> 2 Vitest shards passed, 214 tests passed.
- `pnpm test src/gateway/server-startup-plugins.test.ts src/commands/doctor-bundled-plugin-runtime-deps.test.ts test/scripts/postinstall-bundled-plugins.test.ts test/scripts/bundled-plugin-staged-runtime-deps.test.ts` -> 3 Vitest shards passed, 64 tests passed.

I am closing this as fixed for the BlueBubbles `ERR_MODULE_NOT_FOUND` / plugin-runtime-deps symptom. The broader post-`ready` startup stall / LaunchAgent availability problem is still open in #72846, including current-main reports, so follow-up logs for slow startup should stay there rather than on this runtime-mirror symptom.
