### ISSUE TITLE
[Bug]: 2026.4.25: Gateway hangs/timeouts after update; plugin-runtime-deps missing packages

### ISSUE THREAD

**Issue by Schnup03** [clawdbot/clawdbot#72992]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

I am not very experienced with Linux/WSL, but several Discord users appear to be hitting the same issue, so I am collecting the symptoms here.
Multiple Discord users are reporting serious Gateway failures after updating to OpenClaw 2026.4.25.

Common symptoms:
- `openclaw status` / WS health timeout
- service reports running, but Gateway is unreachable
- `/healthz` sometimes times out or port is not listening
- `Gateway did not become healthy after restart`
- `Completion cache update failed: spawnSync node ETIMEDOUT`
- bundled runtime deps missing:
  - `Cannot find package 'chokidar'`
  - `Cannot find module '@hapi/hoek'`
  - `Cannot find module 'discord-api-types/v10.js'`
  - `Cannot find module 'typebox/build/index.mjs'`
- `npm ENOTEMPTY rename ... node_modules/...`
- browser runtime deps fail to stage: `@modelcontextprotocol/sdk`, `playwright-core`
Affected reports include:
- Gateway not responding after update 2026.4.23 -> 2026.4.25
- Gateway Broken after Update
- Gateway entrypoint problem
- OpenClaw slow after updating to 2026.4.25
- Gateway not starting after updating to 2026.4.25
- qmd memory unavailable / active memory timeouts

One WSL2 case:
- OpenClaw 2026.4.25 aa36ee6
- WSL2 Linux 6.6.87.2
- Node initially 22.22.2, later 24.15.0 via nvm
- systemd user gateway
- bind lan / port 18789
- plugin-runtime-deps root became partially installed
- manual npm install inside plugin-runtime-deps pruned 739 packages
- moving runtime deps aside + doctor did not fully recover consistently
- `OPENCLAW_SKIP_CHANNELS=1 OPENCLAW_SKIP_PROVIDERS=1` can start core after ~30s, but normal service still wedges around channels/runtime deps
- downgrade to 2026.4.23 may not help unless runtime-deps cache/service state are cleaned too

Important warning:
Users should not manually run `npm install` inside `~/.openclaw/plugin-runtime-deps`; it is OpenClaw-managed and npm can prune packages.

Suspected area:
2026.4.25 bundled plugin runtime dependency staging / mirror rebuild / service restart recovery regression, possibly related to issue #72933.

### Steps to reproduce

update from 2026.4.23 > 2026.4.25     

### Expected behavior

works fine after update

### Actual behavior

Dead

### OpenClaw version

2026.4.25

### Operating system

Windows 11 / WSL2  Ubuntu24.04

### Install method

npm

### Model

nicht relevant

### Provider / routing chain

nicht relevant

### Additional provider/model setup details

nicht relevant

### Logs, screenshots, and evidence

```shell

```

**Comment by steipete** [comment]
Confirmed. I reproduced the 2026.4.25 package failure locally: the shipped package can create a managed `openclaw-unknown-*` runtime-deps root and can miss active plugin deps such as `chokidar`, which matches the gateway hangs/timeouts and `ERR_MODULE_NOT_FOUND` reports here.

This is fixed on `main`/the next package by the post-2026.4.25 bundled runtime-deps repair work:

- doctor now repairs the effective startup plugin set, so default memory/browser sidecars are included instead of skipped
- staged runtime mirrors resolve back to the original `openclaw-<version>-<hash>` root instead of deriving `openclaw-unknown-*`
- package-level repair retains the full active dependency set in one managed runtime-deps root

Blacksmith Testbox verification with a packed current `openclaw@2026.4.26` tarball installed into clean temp prefixes/HOMEs:

- default install: `doctor --fix` installed `@modelcontextprotocol/sdk`, `playwright-core`, `chokidar`, `typebox`, `undici`, `ws`, etc.; exactly one `openclaw-2026.4.26-*` stage root; no `openclaw-unknown-*`; `openclaw memory status --json` completed
- Discord-enabled install (`channels.discord.enabled=true`): `doctor --fix` installed `discord-api-types`, `@buape/carbon`, `@discordjs/voice`, `https-proxy-agent`, `opusscript`, plus shared deps; no `openclaw-unknown-*`

Closing as fixed on `main`/next package. Please reopen or file a fresh issue if this still reproduces after updating past 2026.4.25.
