### ISSUE TITLE
[Bug]: Telegram slash commands break after update to 2026.4.21

### ISSUE THREAD

**Issue by r9ntner** [clawdbot/clawdbot#70022]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

Updating OpenClaw from `2026.4.15` to `2026.4.21` broke Telegram native slash commands like `/status` in my setup.

### Steps to reproduce

Environment:
- global npm install
- `/usr/lib/node_modules/openclaw`
- Linux arm64
- Node 24.14.1
- gateway runs as non-root

Gateway stays up, but Telegram logs:

Cannot find module '/usr/lib/node_modules/openclaw/dist/extensions/telegram/bot-native-commands.runtime-<hash>.js'
imported from /usr/lib/node_modules/openclaw/dist/extensions/telegram/bot-<hash>.js

Rollback to 2026.4.15 fixes it.

Possibly related:

• #69858
• #69837
• #69923

### Expected behavior

native slash commands work ;-)

### Actual behavior

no output for native slash commands

### OpenClaw version

2026.4.21

### Operating system

Ubuntu 24.04

### Model

gpt-5.4

### Provider / routing chain

openai-codex/gpt-5.4 · 🔑 oauth

### Logs, screenshots, and evidence

```shell

```

**Comment by Vksh07** [comment]
experiencing the same

**Comment by steipete** [comment]
Closing as fixed in `2026.4.22`.

This was filed against `2026.4.21` and points at a missing Telegram bundled runtime file under `dist/extensions/telegram`. The published `openclaw@2026.4.22` package contains the Telegram native-command runtime files, including `bot-native-commands.runtime-*.js` and `bot-native-commands.delivery.runtime-*.js`, and the related bundled extension packaging/runtime-deps cluster has been verified against `.22`.

Recovery:

```bash
npm install -g openclaw@latest
openclaw doctor --fix
openclaw gateway restart
```

If Telegram native slash commands still fail on `2026.4.22` or newer, please open a fresh issue with the exact version, install method, command/log output, and full missing-file/module path.
